// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/announcementemailbroadcast"
)

// AnnouncementEmailBroadcast is the model entity for the AnnouncementEmailBroadcast schema.
type AnnouncementEmailBroadcast struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AnnouncementID holds the value of the "announcement_id" field.
	AnnouncementID int64 `json:"announcement_id,omitempty"`
	// Subject holds the value of the "subject" field.
	Subject string `json:"subject,omitempty"`
	// BodyHTML holds the value of the "body_html" field.
	BodyHTML string `json:"body_html,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// TotalCount holds the value of the "total_count" field.
	TotalCount int `json:"total_count,omitempty"`
	// SentCount holds the value of the "sent_count" field.
	SentCount int `json:"sent_count,omitempty"`
	// FailedCount holds the value of the "failed_count" field.
	FailedCount int `json:"failed_count,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *int64 `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AnnouncementEmailBroadcast) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case announcementemailbroadcast.FieldID, announcementemailbroadcast.FieldAnnouncementID, announcementemailbroadcast.FieldTotalCount, announcementemailbroadcast.FieldSentCount, announcementemailbroadcast.FieldFailedCount, announcementemailbroadcast.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case announcementemailbroadcast.FieldSubject, announcementemailbroadcast.FieldBodyHTML, announcementemailbroadcast.FieldStatus:
			values[i] = new(sql.NullString)
		case announcementemailbroadcast.FieldCreatedAt, announcementemailbroadcast.FieldStartedAt, announcementemailbroadcast.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AnnouncementEmailBroadcast fields.
func (_m *AnnouncementEmailBroadcast) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case announcementemailbroadcast.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case announcementemailbroadcast.FieldAnnouncementID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field announcement_id", values[i])
			} else if value.Valid {
				_m.AnnouncementID = value.Int64
			}
		case announcementemailbroadcast.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case announcementemailbroadcast.FieldBodyHTML:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body_html", values[i])
			} else if value.Valid {
				_m.BodyHTML = value.String
			}
		case announcementemailbroadcast.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case announcementemailbroadcast.FieldTotalCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_count", values[i])
			} else if value.Valid {
				_m.TotalCount = int(value.Int64)
			}
		case announcementemailbroadcast.FieldSentCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sent_count", values[i])
			} else if value.Valid {
				_m.SentCount = int(value.Int64)
			}
		case announcementemailbroadcast.FieldFailedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failed_count", values[i])
			} else if value.Valid {
				_m.FailedCount = int(value.Int64)
			}
		case announcementemailbroadcast.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(int64)
				*_m.CreatedBy = value.Int64
			}
		case announcementemailbroadcast.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case announcementemailbroadcast.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case announcementemailbroadcast.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AnnouncementEmailBroadcast.
// This includes values selected through modifiers, order, etc.
func (_m *AnnouncementEmailBroadcast) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AnnouncementEmailBroadcast.
// Note that you need to call AnnouncementEmailBroadcast.Unwrap() before calling this method if this AnnouncementEmailBroadcast
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AnnouncementEmailBroadcast) Update() *AnnouncementEmailBroadcastUpdateOne {
	return NewAnnouncementEmailBroadcastClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AnnouncementEmailBroadcast entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AnnouncementEmailBroadcast) Unwrap() *AnnouncementEmailBroadcast {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AnnouncementEmailBroadcast is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AnnouncementEmailBroadcast) String() string {
	var builder strings.Builder
	builder.WriteString("AnnouncementEmailBroadcast(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("announcement_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AnnouncementID))
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("body_html=")
	builder.WriteString(_m.BodyHTML)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("total_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCount))
	builder.WriteString(", ")
	builder.WriteString("sent_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SentCount))
	builder.WriteString(", ")
	builder.WriteString("failed_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailedCount))
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AnnouncementEmailBroadcasts is a parsable slice of AnnouncementEmailBroadcast.
type AnnouncementEmailBroadcasts []*AnnouncementEmailBroadcast
