// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcementemailbroadcast"
)

// AnnouncementEmailBroadcastCreate is the builder for creating a AnnouncementEmailBroadcast entity.
type AnnouncementEmailBroadcastCreate struct {
	config
	mutation *AnnouncementEmailBroadcastMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAnnouncementID sets the "announcement_id" field.
func (_c *AnnouncementEmailBroadcastCreate) SetAnnouncementID(v int64) *AnnouncementEmailBroadcastCreate {
	_c.mutation.SetAnnouncementID(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *AnnouncementEmailBroadcastCreate) SetSubject(v string) *AnnouncementEmailBroadcastCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetBodyHTML sets the "body_html" field.
func (_c *AnnouncementEmailBroadcastCreate) SetBodyHTML(v string) *AnnouncementEmailBroadcastCreate {
	_c.mutation.SetBodyHTML(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AnnouncementEmailBroadcastCreate) SetStatus(v string) *AnnouncementEmailBroadcastCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AnnouncementEmailBroadcastCreate) SetNillableStatus(v *string) *AnnouncementEmailBroadcastCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTotalCount sets the "total_count" field.
func (_c *AnnouncementEmailBroadcastCreate) SetTotalCount(v int) *AnnouncementEmailBroadcastCreate {
	_c.mutation.SetTotalCount(v)
	return _c
}

// SetNillableTotalCount sets the "total_count" field if the given value is not nil.
func (_c *AnnouncementEmailBroadcastCreate) SetNillableTotalCount(v *int) *AnnouncementEmailBroadcastCreate {
	if v != nil {
		_c.SetTotalCount(*v)
	}
	return _c
}

// SetSentCount sets the "sent_count" field.
func (_c *AnnouncementEmailBroadcastCreate) SetSentCount(v int) *AnnouncementEmailBroadcastCreate {
	_c.mutation.SetSentCount(v)
	return _c
}

// SetNillableSentCount sets the "sent_count" field if the given value is not nil.
func (_c *AnnouncementEmailBroadcastCreate) SetNillableSentCount(v *int) *AnnouncementEmailBroadcastCreate {
	if v != nil {
		_c.SetSentCount(*v)
	}
	return _c
}

// SetFailedCount sets the "failed_count" field.
func (_c *AnnouncementEmailBroadcastCreate) SetFailedCount(v int) *AnnouncementEmailBroadcastCreate {
	_c.mutation.SetFailedCount(v)
	return _c
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_c *AnnouncementEmailBroadcastCreate) SetNillableFailedCount(v *int) *AnnouncementEmailBroadcastCreate {
	if v != nil {
		_c.SetFailedCount(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *AnnouncementEmailBroadcastCreate) SetCreatedBy(v int64) *AnnouncementEmailBroadcastCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *AnnouncementEmailBroadcastCreate) SetNillableCreatedBy(v *int64) *AnnouncementEmailBroadcastCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AnnouncementEmailBroadcastCreate) SetCreatedAt(v time.Time) *AnnouncementEmailBroadcastCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AnnouncementEmailBroadcastCreate) SetNillableCreatedAt(v *time.Time) *AnnouncementEmailBroadcastCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *AnnouncementEmailBroadcastCreate) SetStartedAt(v time.Time) *AnnouncementEmailBroadcastCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *AnnouncementEmailBroadcastCreate) SetNillableStartedAt(v *time.Time) *AnnouncementEmailBroadcastCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *AnnouncementEmailBroadcastCreate) SetCompletedAt(v time.Time) *AnnouncementEmailBroadcastCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *AnnouncementEmailBroadcastCreate) SetNillableCompletedAt(v *time.Time) *AnnouncementEmailBroadcastCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// Mutation returns the AnnouncementEmailBroadcastMutation object of the builder.
func (_c *AnnouncementEmailBroadcastCreate) Mutation() *AnnouncementEmailBroadcastMutation {
	return _c.mutation
}

// Save creates the AnnouncementEmailBroadcast in the database.
func (_c *AnnouncementEmailBroadcastCreate) Save(ctx context.Context) (*AnnouncementEmailBroadcast, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AnnouncementEmailBroadcastCreate) SaveX(ctx context.Context) *AnnouncementEmailBroadcast {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnnouncementEmailBroadcastCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnnouncementEmailBroadcastCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AnnouncementEmailBroadcastCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := announcementemailbroadcast.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TotalCount(); !ok {
		v := announcementemailbroadcast.DefaultTotalCount
		_c.mutation.SetTotalCount(v)
	}
	if _, ok := _c.mutation.SentCount(); !ok {
		v := announcementemailbroadcast.DefaultSentCount
		_c.mutation.SetSentCount(v)
	}
	if _, ok := _c.mutation.FailedCount(); !ok {
		v := announcementemailbroadcast.DefaultFailedCount
		_c.mutation.SetFailedCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := announcementemailbroadcast.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AnnouncementEmailBroadcastCreate) check() error {
	if _, ok := _c.mutation.AnnouncementID(); !ok {
		return &ValidationError{Name: "announcement_id", err: errors.New(`ent: missing required field "AnnouncementEmailBroadcast.announcement_id"`)}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "AnnouncementEmailBroadcast.subject"`)}
	}
	if _, ok := _c.mutation.BodyHTML(); !ok {
		return &ValidationError{Name: "body_html", err: errors.New(`ent: missing required field "AnnouncementEmailBroadcast.body_html"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AnnouncementEmailBroadcast.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := announcementemailbroadcast.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AnnouncementEmailBroadcast.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalCount(); !ok {
		return &ValidationError{Name: "total_count", err: errors.New(`ent: missing required field "AnnouncementEmailBroadcast.total_count"`)}
	}
	if _, ok := _c.mutation.SentCount(); !ok {
		return &ValidationError{Name: "sent_count", err: errors.New(`ent: missing required field "AnnouncementEmailBroadcast.sent_count"`)}
	}
	if _, ok := _c.mutation.FailedCount(); !ok {
		return &ValidationError{Name: "failed_count", err: errors.New(`ent: missing required field "AnnouncementEmailBroadcast.failed_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AnnouncementEmailBroadcast.created_at"`)}
	}
	return nil
}

func (_c *AnnouncementEmailBroadcastCreate) sqlSave(ctx context.Context) (*AnnouncementEmailBroadcast, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AnnouncementEmailBroadcastCreate) createSpec() (*AnnouncementEmailBroadcast, *sqlgraph.CreateSpec) {
	var (
		_node = &AnnouncementEmailBroadcast{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(announcementemailbroadcast.Table, sqlgraph.NewFieldSpec(announcementemailbroadcast.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AnnouncementID(); ok {
		_spec.SetField(announcementemailbroadcast.FieldAnnouncementID, field.TypeInt64, value)
		_node.AnnouncementID = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(announcementemailbroadcast.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.BodyHTML(); ok {
		_spec.SetField(announcementemailbroadcast.FieldBodyHTML, field.TypeString, value)
		_node.BodyHTML = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(announcementemailbroadcast.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TotalCount(); ok {
		_spec.SetField(announcementemailbroadcast.FieldTotalCount, field.TypeInt, value)
		_node.TotalCount = value
	}
	if value, ok := _c.mutation.SentCount(); ok {
		_spec.SetField(announcementemailbroadcast.FieldSentCount, field.TypeInt, value)
		_node.SentCount = value
	}
	if value, ok := _c.mutation.FailedCount(); ok {
		_spec.SetField(announcementemailbroadcast.FieldFailedCount, field.TypeInt, value)
		_node.FailedCount = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(announcementemailbroadcast.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(announcementemailbroadcast.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(announcementemailbroadcast.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(announcementemailbroadcast.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AnnouncementEmailBroadcast.Create().
//		SetAnnouncementID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AnnouncementEmailBroadcastUpsert) {
//			SetAnnouncementID(v+v).
//		}).
//		Exec(ctx)
func (_c *AnnouncementEmailBroadcastCreate) OnConflict(opts ...sql.ConflictOption) *AnnouncementEmailBroadcastUpsertOne {
	_c.conflict = opts
	return &AnnouncementEmailBroadcastUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AnnouncementEmailBroadcast.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AnnouncementEmailBroadcastCreate) OnConflictColumns(columns ...string) *AnnouncementEmailBroadcastUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AnnouncementEmailBroadcastUpsertOne{
		create: _c,
	}
}

type (
	// AnnouncementEmailBroadcastUpsertOne is the builder for "upsert"-ing
	//  one AnnouncementEmailBroadcast node.
	AnnouncementEmailBroadcastUpsertOne struct {
		create *AnnouncementEmailBroadcastCreate
	}

	// AnnouncementEmailBroadcastUpsert is the "OnConflict" setter.
	AnnouncementEmailBroadcastUpsert struct {
		*sql.UpdateSet
	}
)

// SetAnnouncementID sets the "announcement_id" field.
func (u *AnnouncementEmailBroadcastUpsert) SetAnnouncementID(v int64) *AnnouncementEmailBroadcastUpsert {
	u.Set(announcementemailbroadcast.FieldAnnouncementID, v)
	return u
}

// UpdateAnnouncementID sets the "announcement_id" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsert) UpdateAnnouncementID() *AnnouncementEmailBroadcastUpsert {
	u.SetExcluded(announcementemailbroadcast.FieldAnnouncementID)
	return u
}

// AddAnnouncementID adds v to the "announcement_id" field.
func (u *AnnouncementEmailBroadcastUpsert) AddAnnouncementID(v int64) *AnnouncementEmailBroadcastUpsert {
	u.Add(announcementemailbroadcast.FieldAnnouncementID, v)
	return u
}

// SetSubject sets the "subject" field.
func (u *AnnouncementEmailBroadcastUpsert) SetSubject(v string) *AnnouncementEmailBroadcastUpsert {
	u.Set(announcementemailbroadcast.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsert) UpdateSubject() *AnnouncementEmailBroadcastUpsert {
	u.SetExcluded(announcementemailbroadcast.FieldSubject)
	return u
}

// SetBodyHTML sets the "body_html" field.
func (u *AnnouncementEmailBroadcastUpsert) SetBodyHTML(v string) *AnnouncementEmailBroadcastUpsert {
	u.Set(announcementemailbroadcast.FieldBodyHTML, v)
	return u
}

// UpdateBodyHTML sets the "body_html" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsert) UpdateBodyHTML() *AnnouncementEmailBroadcastUpsert {
	u.SetExcluded(announcementemailbroadcast.FieldBodyHTML)
	return u
}

// SetStatus sets the "status" field.
func (u *AnnouncementEmailBroadcastUpsert) SetStatus(v string) *AnnouncementEmailBroadcastUpsert {
	u.Set(announcementemailbroadcast.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsert) UpdateStatus() *AnnouncementEmailBroadcastUpsert {
	u.SetExcluded(announcementemailbroadcast.FieldStatus)
	return u
}

// SetTotalCount sets the "total_count" field.
func (u *AnnouncementEmailBroadcastUpsert) SetTotalCount(v int) *AnnouncementEmailBroadcastUpsert {
	u.Set(announcementemailbroadcast.FieldTotalCount, v)
	return u
}

// UpdateTotalCount sets the "total_count" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsert) UpdateTotalCount() *AnnouncementEmailBroadcastUpsert {
	u.SetExcluded(announcementemailbroadcast.FieldTotalCount)
	return u
}

// AddTotalCount adds v to the "total_count" field.
func (u *AnnouncementEmailBroadcastUpsert) AddTotalCount(v int) *AnnouncementEmailBroadcastUpsert {
	u.Add(announcementemailbroadcast.FieldTotalCount, v)
	return u
}

// SetSentCount sets the "sent_count" field.
func (u *AnnouncementEmailBroadcastUpsert) SetSentCount(v int) *AnnouncementEmailBroadcastUpsert {
	u.Set(announcementemailbroadcast.FieldSentCount, v)
	return u
}

// UpdateSentCount sets the "sent_count" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsert) UpdateSentCount() *AnnouncementEmailBroadcastUpsert {
	u.SetExcluded(announcementemailbroadcast.FieldSentCount)
	return u
}

// AddSentCount adds v to the "sent_count" field.
func (u *AnnouncementEmailBroadcastUpsert) AddSentCount(v int) *AnnouncementEmailBroadcastUpsert {
	u.Add(announcementemailbroadcast.FieldSentCount, v)
	return u
}

// SetFailedCount sets the "failed_count" field.
func (u *AnnouncementEmailBroadcastUpsert) SetFailedCount(v int) *AnnouncementEmailBroadcastUpsert {
	u.Set(announcementemailbroadcast.FieldFailedCount, v)
	return u
}

// UpdateFailedCount sets the "failed_count" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsert) UpdateFailedCount() *AnnouncementEmailBroadcastUpsert {
	u.SetExcluded(announcementemailbroadcast.FieldFailedCount)
	return u
}

// AddFailedCount adds v to the "failed_count" field.
func (u *AnnouncementEmailBroadcastUpsert) AddFailedCount(v int) *AnnouncementEmailBroadcastUpsert {
	u.Add(announcementemailbroadcast.FieldFailedCount, v)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *AnnouncementEmailBroadcastUpsert) SetCreatedBy(v int64) *AnnouncementEmailBroadcastUpsert {
	u.Set(announcementemailbroadcast.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsert) UpdateCreatedBy() *AnnouncementEmailBroadcastUpsert {
	u.SetExcluded(announcementemailbroadcast.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AnnouncementEmailBroadcastUpsert) AddCreatedBy(v int64) *AnnouncementEmailBroadcastUpsert {
	u.Add(announcementemailbroadcast.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *AnnouncementEmailBroadcastUpsert) ClearCreatedBy() *AnnouncementEmailBroadcastUpsert {
	u.SetNull(announcementemailbroadcast.FieldCreatedBy)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *AnnouncementEmailBroadcastUpsert) SetCreatedAt(v time.Time) *AnnouncementEmailBroadcastUpsert {
	u.Set(announcementemailbroadcast.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsert) UpdateCreatedAt() *AnnouncementEmailBroadcastUpsert {
	u.SetExcluded(announcementemailbroadcast.FieldCreatedAt)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *AnnouncementEmailBroadcastUpsert) SetStartedAt(v time.Time) *AnnouncementEmailBroadcastUpsert {
	u.Set(announcementemailbroadcast.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsert) UpdateStartedAt() *AnnouncementEmailBroadcastUpsert {
	u.SetExcluded(announcementemailbroadcast.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *AnnouncementEmailBroadcastUpsert) ClearStartedAt() *AnnouncementEmailBroadcastUpsert {
	u.SetNull(announcementemailbroadcast.FieldStartedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *AnnouncementEmailBroadcastUpsert) SetCompletedAt(v time.Time) *AnnouncementEmailBroadcastUpsert {
	u.Set(announcementemailbroadcast.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsert) UpdateCompletedAt() *AnnouncementEmailBroadcastUpsert {
	u.SetExcluded(announcementemailbroadcast.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *AnnouncementEmailBroadcastUpsert) ClearCompletedAt() *AnnouncementEmailBroadcastUpsert {
	u.SetNull(announcementemailbroadcast.FieldCompletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AnnouncementEmailBroadcast.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AnnouncementEmailBroadcastUpsertOne) UpdateNewValues() *AnnouncementEmailBroadcastUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AnnouncementEmailBroadcast.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AnnouncementEmailBroadcastUpsertOne) Ignore() *AnnouncementEmailBroadcastUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AnnouncementEmailBroadcastUpsertOne) DoNothing() *AnnouncementEmailBroadcastUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AnnouncementEmailBroadcastCreate.OnConflict
// documentation for more info.
func (u *AnnouncementEmailBroadcastUpsertOne) Update(set func(*AnnouncementEmailBroadcastUpsert)) *AnnouncementEmailBroadcastUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AnnouncementEmailBroadcastUpsert{UpdateSet: update})
	}))
	return u
}

// SetAnnouncementID sets the "announcement_id" field.
func (u *AnnouncementEmailBroadcastUpsertOne) SetAnnouncementID(v int64) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetAnnouncementID(v)
	})
}

// AddAnnouncementID adds v to the "announcement_id" field.
func (u *AnnouncementEmailBroadcastUpsertOne) AddAnnouncementID(v int64) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.AddAnnouncementID(v)
	})
}

// UpdateAnnouncementID sets the "announcement_id" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertOne) UpdateAnnouncementID() *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateAnnouncementID()
	})
}

// SetSubject sets the "subject" field.
func (u *AnnouncementEmailBroadcastUpsertOne) SetSubject(v string) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertOne) UpdateSubject() *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateSubject()
	})
}

// SetBodyHTML sets the "body_html" field.
func (u *AnnouncementEmailBroadcastUpsertOne) SetBodyHTML(v string) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetBodyHTML(v)
	})
}

// UpdateBodyHTML sets the "body_html" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertOne) UpdateBodyHTML() *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateBodyHTML()
	})
}

// SetStatus sets the "status" field.
func (u *AnnouncementEmailBroadcastUpsertOne) SetStatus(v string) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertOne) UpdateStatus() *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateStatus()
	})
}

// SetTotalCount sets the "total_count" field.
func (u *AnnouncementEmailBroadcastUpsertOne) SetTotalCount(v int) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetTotalCount(v)
	})
}

// AddTotalCount adds v to the "total_count" field.
func (u *AnnouncementEmailBroadcastUpsertOne) AddTotalCount(v int) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.AddTotalCount(v)
	})
}

// UpdateTotalCount sets the "total_count" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertOne) UpdateTotalCount() *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateTotalCount()
	})
}

// SetSentCount sets the "sent_count" field.
func (u *AnnouncementEmailBroadcastUpsertOne) SetSentCount(v int) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetSentCount(v)
	})
}

// AddSentCount adds v to the "sent_count" field.
func (u *AnnouncementEmailBroadcastUpsertOne) AddSentCount(v int) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.AddSentCount(v)
	})
}

// UpdateSentCount sets the "sent_count" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertOne) UpdateSentCount() *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateSentCount()
	})
}

// SetFailedCount sets the "failed_count" field.
func (u *AnnouncementEmailBroadcastUpsertOne) SetFailedCount(v int) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetFailedCount(v)
	})
}

// AddFailedCount adds v to the "failed_count" field.
func (u *AnnouncementEmailBroadcastUpsertOne) AddFailedCount(v int) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.AddFailedCount(v)
	})
}

// UpdateFailedCount sets the "failed_count" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertOne) UpdateFailedCount() *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateFailedCount()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *AnnouncementEmailBroadcastUpsertOne) SetCreatedBy(v int64) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AnnouncementEmailBroadcastUpsertOne) AddCreatedBy(v int64) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertOne) UpdateCreatedBy() *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *AnnouncementEmailBroadcastUpsertOne) ClearCreatedBy() *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.ClearCreatedBy()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AnnouncementEmailBroadcastUpsertOne) SetCreatedAt(v time.Time) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertOne) UpdateCreatedAt() *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *AnnouncementEmailBroadcastUpsertOne) SetStartedAt(v time.Time) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertOne) UpdateStartedAt() *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *AnnouncementEmailBroadcastUpsertOne) ClearStartedAt() *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *AnnouncementEmailBroadcastUpsertOne) SetCompletedAt(v time.Time) *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertOne) UpdateCompletedAt() *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *AnnouncementEmailBroadcastUpsertOne) ClearCompletedAt() *AnnouncementEmailBroadcastUpsertOne {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *AnnouncementEmailBroadcastUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AnnouncementEmailBroadcastCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AnnouncementEmailBroadcastUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AnnouncementEmailBroadcastUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AnnouncementEmailBroadcastUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AnnouncementEmailBroadcastCreateBulk is the builder for creating many AnnouncementEmailBroadcast entities in bulk.
type AnnouncementEmailBroadcastCreateBulk struct {
	config
	err      error
	builders []*AnnouncementEmailBroadcastCreate
	conflict []sql.ConflictOption
}

// Save creates the AnnouncementEmailBroadcast entities in the database.
func (_c *AnnouncementEmailBroadcastCreateBulk) Save(ctx context.Context) ([]*AnnouncementEmailBroadcast, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AnnouncementEmailBroadcast, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnnouncementEmailBroadcastMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AnnouncementEmailBroadcastCreateBulk) SaveX(ctx context.Context) []*AnnouncementEmailBroadcast {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnnouncementEmailBroadcastCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnnouncementEmailBroadcastCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AnnouncementEmailBroadcast.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AnnouncementEmailBroadcastUpsert) {
//			SetAnnouncementID(v+v).
//		}).
//		Exec(ctx)
func (_c *AnnouncementEmailBroadcastCreateBulk) OnConflict(opts ...sql.ConflictOption) *AnnouncementEmailBroadcastUpsertBulk {
	_c.conflict = opts
	return &AnnouncementEmailBroadcastUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AnnouncementEmailBroadcast.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AnnouncementEmailBroadcastCreateBulk) OnConflictColumns(columns ...string) *AnnouncementEmailBroadcastUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AnnouncementEmailBroadcastUpsertBulk{
		create: _c,
	}
}

// AnnouncementEmailBroadcastUpsertBulk is the builder for "upsert"-ing
// a bulk of AnnouncementEmailBroadcast nodes.
type AnnouncementEmailBroadcastUpsertBulk struct {
	create *AnnouncementEmailBroadcastCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AnnouncementEmailBroadcast.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AnnouncementEmailBroadcastUpsertBulk) UpdateNewValues() *AnnouncementEmailBroadcastUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AnnouncementEmailBroadcast.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AnnouncementEmailBroadcastUpsertBulk) Ignore() *AnnouncementEmailBroadcastUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AnnouncementEmailBroadcastUpsertBulk) DoNothing() *AnnouncementEmailBroadcastUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AnnouncementEmailBroadcastCreateBulk.OnConflict
// documentation for more info.
func (u *AnnouncementEmailBroadcastUpsertBulk) Update(set func(*AnnouncementEmailBroadcastUpsert)) *AnnouncementEmailBroadcastUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AnnouncementEmailBroadcastUpsert{UpdateSet: update})
	}))
	return u
}

// SetAnnouncementID sets the "announcement_id" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) SetAnnouncementID(v int64) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetAnnouncementID(v)
	})
}

// AddAnnouncementID adds v to the "announcement_id" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) AddAnnouncementID(v int64) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.AddAnnouncementID(v)
	})
}

// UpdateAnnouncementID sets the "announcement_id" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertBulk) UpdateAnnouncementID() *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateAnnouncementID()
	})
}

// SetSubject sets the "subject" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) SetSubject(v string) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertBulk) UpdateSubject() *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateSubject()
	})
}

// SetBodyHTML sets the "body_html" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) SetBodyHTML(v string) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetBodyHTML(v)
	})
}

// UpdateBodyHTML sets the "body_html" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertBulk) UpdateBodyHTML() *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateBodyHTML()
	})
}

// SetStatus sets the "status" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) SetStatus(v string) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertBulk) UpdateStatus() *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateStatus()
	})
}

// SetTotalCount sets the "total_count" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) SetTotalCount(v int) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetTotalCount(v)
	})
}

// AddTotalCount adds v to the "total_count" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) AddTotalCount(v int) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.AddTotalCount(v)
	})
}

// UpdateTotalCount sets the "total_count" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertBulk) UpdateTotalCount() *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateTotalCount()
	})
}

// SetSentCount sets the "sent_count" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) SetSentCount(v int) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetSentCount(v)
	})
}

// AddSentCount adds v to the "sent_count" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) AddSentCount(v int) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.AddSentCount(v)
	})
}

// UpdateSentCount sets the "sent_count" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertBulk) UpdateSentCount() *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateSentCount()
	})
}

// SetFailedCount sets the "failed_count" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) SetFailedCount(v int) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetFailedCount(v)
	})
}

// AddFailedCount adds v to the "failed_count" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) AddFailedCount(v int) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.AddFailedCount(v)
	})
}

// UpdateFailedCount sets the "failed_count" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertBulk) UpdateFailedCount() *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateFailedCount()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) SetCreatedBy(v int64) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) AddCreatedBy(v int64) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertBulk) UpdateCreatedBy() *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) ClearCreatedBy() *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.ClearCreatedBy()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) SetCreatedAt(v time.Time) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertBulk) UpdateCreatedAt() *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) SetStartedAt(v time.Time) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertBulk) UpdateStartedAt() *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) ClearStartedAt() *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) SetCompletedAt(v time.Time) *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *AnnouncementEmailBroadcastUpsertBulk) UpdateCompletedAt() *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *AnnouncementEmailBroadcastUpsertBulk) ClearCompletedAt() *AnnouncementEmailBroadcastUpsertBulk {
	return u.Update(func(s *AnnouncementEmailBroadcastUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *AnnouncementEmailBroadcastUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AnnouncementEmailBroadcastCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AnnouncementEmailBroadcastCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AnnouncementEmailBroadcastUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
