// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcementemaildelivery"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AnnouncementEmailDeliveryUpdate is the builder for updating AnnouncementEmailDelivery entities.
type AnnouncementEmailDeliveryUpdate struct {
	config
	hooks    []Hook
	mutation *AnnouncementEmailDeliveryMutation
}

// Where appends a list predicates to the AnnouncementEmailDeliveryUpdate builder.
func (_u *AnnouncementEmailDeliveryUpdate) Where(ps ...predicate.AnnouncementEmailDelivery) *AnnouncementEmailDeliveryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBroadcastID sets the "broadcast_id" field.
func (_u *AnnouncementEmailDeliveryUpdate) SetBroadcastID(v int64) *AnnouncementEmailDeliveryUpdate {
	_u.mutation.ResetBroadcastID()
	_u.mutation.SetBroadcastID(v)
	return _u
}

// SetNillableBroadcastID sets the "broadcast_id" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdate) SetNillableBroadcastID(v *int64) *AnnouncementEmailDeliveryUpdate {
	if v != nil {
		_u.SetBroadcastID(*v)
	}
	return _u
}

// AddBroadcastID adds value to the "broadcast_id" field.
func (_u *AnnouncementEmailDeliveryUpdate) AddBroadcastID(v int64) *AnnouncementEmailDeliveryUpdate {
	_u.mutation.AddBroadcastID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AnnouncementEmailDeliveryUpdate) SetUserID(v int64) *AnnouncementEmailDeliveryUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdate) SetNillableUserID(v *int64) *AnnouncementEmailDeliveryUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AnnouncementEmailDeliveryUpdate) AddUserID(v int64) *AnnouncementEmailDeliveryUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AnnouncementEmailDeliveryUpdate) ClearUserID() *AnnouncementEmailDeliveryUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetEmail sets the "email" field.
func (_u *AnnouncementEmailDeliveryUpdate) SetEmail(v string) *AnnouncementEmailDeliveryUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdate) SetNillableEmail(v *string) *AnnouncementEmailDeliveryUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AnnouncementEmailDeliveryUpdate) SetStatus(v string) *AnnouncementEmailDeliveryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdate) SetNillableStatus(v *string) *AnnouncementEmailDeliveryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *AnnouncementEmailDeliveryUpdate) SetAttemptCount(v int) *AnnouncementEmailDeliveryUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdate) SetNillableAttemptCount(v *int) *AnnouncementEmailDeliveryUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *AnnouncementEmailDeliveryUpdate) AddAttemptCount(v int) *AnnouncementEmailDeliveryUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *AnnouncementEmailDeliveryUpdate) SetLeaseExpiresAt(v time.Time) *AnnouncementEmailDeliveryUpdate {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdate) SetNillableLeaseExpiresAt(v *time.Time) *AnnouncementEmailDeliveryUpdate {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (_u *AnnouncementEmailDeliveryUpdate) ClearLeaseExpiresAt() *AnnouncementEmailDeliveryUpdate {
	_u.mutation.ClearLeaseExpiresAt()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *AnnouncementEmailDeliveryUpdate) SetErrorMessage(v string) *AnnouncementEmailDeliveryUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdate) SetNillableErrorMessage(v *string) *AnnouncementEmailDeliveryUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *AnnouncementEmailDeliveryUpdate) ClearErrorMessage() *AnnouncementEmailDeliveryUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetLastAttemptAt sets the "last_attempt_at" field.
func (_u *AnnouncementEmailDeliveryUpdate) SetLastAttemptAt(v time.Time) *AnnouncementEmailDeliveryUpdate {
	_u.mutation.SetLastAttemptAt(v)
	return _u
}

// SetNillableLastAttemptAt sets the "last_attempt_at" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdate) SetNillableLastAttemptAt(v *time.Time) *AnnouncementEmailDeliveryUpdate {
	if v != nil {
		_u.SetLastAttemptAt(*v)
	}
	return _u
}

// ClearLastAttemptAt clears the value of the "last_attempt_at" field.
func (_u *AnnouncementEmailDeliveryUpdate) ClearLastAttemptAt() *AnnouncementEmailDeliveryUpdate {
	_u.mutation.ClearLastAttemptAt()
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *AnnouncementEmailDeliveryUpdate) SetSentAt(v time.Time) *AnnouncementEmailDeliveryUpdate {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdate) SetNillableSentAt(v *time.Time) *AnnouncementEmailDeliveryUpdate {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *AnnouncementEmailDeliveryUpdate) ClearSentAt() *AnnouncementEmailDeliveryUpdate {
	_u.mutation.ClearSentAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AnnouncementEmailDeliveryUpdate) SetCreatedAt(v time.Time) *AnnouncementEmailDeliveryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdate) SetNillableCreatedAt(v *time.Time) *AnnouncementEmailDeliveryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the AnnouncementEmailDeliveryMutation object of the builder.
func (_u *AnnouncementEmailDeliveryUpdate) Mutation() *AnnouncementEmailDeliveryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnnouncementEmailDeliveryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementEmailDeliveryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnnouncementEmailDeliveryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementEmailDeliveryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementEmailDeliveryUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := announcementemaildelivery.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AnnouncementEmailDelivery.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := announcementemaildelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AnnouncementEmailDelivery.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := announcementemaildelivery.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "AnnouncementEmailDelivery.error_message": %w`, err)}
		}
	}
	return nil
}

func (_u *AnnouncementEmailDeliveryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcementemaildelivery.Table, announcementemaildelivery.Columns, sqlgraph.NewFieldSpec(announcementemaildelivery.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BroadcastID(); ok {
		_spec.SetField(announcementemaildelivery.FieldBroadcastID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBroadcastID(); ok {
		_spec.AddField(announcementemaildelivery.FieldBroadcastID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(announcementemaildelivery.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(announcementemaildelivery.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(announcementemaildelivery.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(announcementemaildelivery.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(announcementemaildelivery.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(announcementemaildelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(announcementemaildelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(announcementemaildelivery.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LeaseExpiresAtCleared() {
		_spec.ClearField(announcementemaildelivery.FieldLeaseExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(announcementemaildelivery.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(announcementemaildelivery.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.LastAttemptAt(); ok {
		_spec.SetField(announcementemaildelivery.FieldLastAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.LastAttemptAtCleared() {
		_spec.ClearField(announcementemaildelivery.FieldLastAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(announcementemaildelivery.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(announcementemaildelivery.FieldSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(announcementemaildelivery.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcementemaildelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnnouncementEmailDeliveryUpdateOne is the builder for updating a single AnnouncementEmailDelivery entity.
type AnnouncementEmailDeliveryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnnouncementEmailDeliveryMutation
}

// SetBroadcastID sets the "broadcast_id" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetBroadcastID(v int64) *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.ResetBroadcastID()
	_u.mutation.SetBroadcastID(v)
	return _u
}

// SetNillableBroadcastID sets the "broadcast_id" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetNillableBroadcastID(v *int64) *AnnouncementEmailDeliveryUpdateOne {
	if v != nil {
		_u.SetBroadcastID(*v)
	}
	return _u
}

// AddBroadcastID adds value to the "broadcast_id" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) AddBroadcastID(v int64) *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.AddBroadcastID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetUserID(v int64) *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetNillableUserID(v *int64) *AnnouncementEmailDeliveryUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) AddUserID(v int64) *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) ClearUserID() *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetEmail sets the "email" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetEmail(v string) *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetNillableEmail(v *string) *AnnouncementEmailDeliveryUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetStatus(v string) *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetNillableStatus(v *string) *AnnouncementEmailDeliveryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetAttemptCount(v int) *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetNillableAttemptCount(v *int) *AnnouncementEmailDeliveryUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) AddAttemptCount(v int) *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetLeaseExpiresAt(v time.Time) *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetNillableLeaseExpiresAt(v *time.Time) *AnnouncementEmailDeliveryUpdateOne {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) ClearLeaseExpiresAt() *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.ClearLeaseExpiresAt()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetErrorMessage(v string) *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetNillableErrorMessage(v *string) *AnnouncementEmailDeliveryUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) ClearErrorMessage() *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetLastAttemptAt sets the "last_attempt_at" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetLastAttemptAt(v time.Time) *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.SetLastAttemptAt(v)
	return _u
}

// SetNillableLastAttemptAt sets the "last_attempt_at" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetNillableLastAttemptAt(v *time.Time) *AnnouncementEmailDeliveryUpdateOne {
	if v != nil {
		_u.SetLastAttemptAt(*v)
	}
	return _u
}

// ClearLastAttemptAt clears the value of the "last_attempt_at" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) ClearLastAttemptAt() *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.ClearLastAttemptAt()
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetSentAt(v time.Time) *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetNillableSentAt(v *time.Time) *AnnouncementEmailDeliveryUpdateOne {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) ClearSentAt() *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.ClearSentAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetCreatedAt(v time.Time) *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AnnouncementEmailDeliveryUpdateOne) SetNillableCreatedAt(v *time.Time) *AnnouncementEmailDeliveryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the AnnouncementEmailDeliveryMutation object of the builder.
func (_u *AnnouncementEmailDeliveryUpdateOne) Mutation() *AnnouncementEmailDeliveryMutation {
	return _u.mutation
}

// Where appends a list predicates to the AnnouncementEmailDeliveryUpdate builder.
func (_u *AnnouncementEmailDeliveryUpdateOne) Where(ps ...predicate.AnnouncementEmailDelivery) *AnnouncementEmailDeliveryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnnouncementEmailDeliveryUpdateOne) Select(field string, fields ...string) *AnnouncementEmailDeliveryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AnnouncementEmailDelivery entity.
func (_u *AnnouncementEmailDeliveryUpdateOne) Save(ctx context.Context) (*AnnouncementEmailDelivery, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementEmailDeliveryUpdateOne) SaveX(ctx context.Context) *AnnouncementEmailDelivery {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnnouncementEmailDeliveryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementEmailDeliveryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementEmailDeliveryUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := announcementemaildelivery.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AnnouncementEmailDelivery.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := announcementemaildelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AnnouncementEmailDelivery.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := announcementemaildelivery.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "AnnouncementEmailDelivery.error_message": %w`, err)}
		}
	}
	return nil
}

func (_u *AnnouncementEmailDeliveryUpdateOne) sqlSave(ctx context.Context) (_node *AnnouncementEmailDelivery, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcementemaildelivery.Table, announcementemaildelivery.Columns, sqlgraph.NewFieldSpec(announcementemaildelivery.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AnnouncementEmailDelivery.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, announcementemaildelivery.FieldID)
		for _, f := range fields {
			if !announcementemaildelivery.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != announcementemaildelivery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BroadcastID(); ok {
		_spec.SetField(announcementemaildelivery.FieldBroadcastID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBroadcastID(); ok {
		_spec.AddField(announcementemaildelivery.FieldBroadcastID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(announcementemaildelivery.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(announcementemaildelivery.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(announcementemaildelivery.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(announcementemaildelivery.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(announcementemaildelivery.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(announcementemaildelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(announcementemaildelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(announcementemaildelivery.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LeaseExpiresAtCleared() {
		_spec.ClearField(announcementemaildelivery.FieldLeaseExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(announcementemaildelivery.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(announcementemaildelivery.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.LastAttemptAt(); ok {
		_spec.SetField(announcementemaildelivery.FieldLastAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.LastAttemptAtCleared() {
		_spec.ClearField(announcementemaildelivery.FieldLastAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(announcementemaildelivery.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(announcementemaildelivery.FieldSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(announcementemaildelivery.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &AnnouncementEmailDelivery{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcementemaildelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
