// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcementemailbroadcast"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AnnouncementEmailBroadcastDelete is the builder for deleting a AnnouncementEmailBroadcast entity.
type AnnouncementEmailBroadcastDelete struct {
	config
	hooks    []Hook
	mutation *AnnouncementEmailBroadcastMutation
}

// Where appends a list predicates to the AnnouncementEmailBroadcastDelete builder.
func (_d *AnnouncementEmailBroadcastDelete) Where(ps ...predicate.AnnouncementEmailBroadcast) *AnnouncementEmailBroadcastDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AnnouncementEmailBroadcastDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AnnouncementEmailBroadcastDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AnnouncementEmailBroadcastDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(announcementemailbroadcast.Table, sqlgraph.NewFieldSpec(announcementemailbroadcast.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AnnouncementEmailBroadcastDeleteOne is the builder for deleting a single AnnouncementEmailBroadcast entity.
type AnnouncementEmailBroadcastDeleteOne struct {
	_d *AnnouncementEmailBroadcastDelete
}

// Where appends a list predicates to the AnnouncementEmailBroadcastDelete builder.
func (_d *AnnouncementEmailBroadcastDeleteOne) Where(ps ...predicate.AnnouncementEmailBroadcast) *AnnouncementEmailBroadcastDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AnnouncementEmailBroadcastDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{announcementemailbroadcast.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AnnouncementEmailBroadcastDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
