// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcementemailbroadcast"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AnnouncementEmailBroadcastUpdate is the builder for updating AnnouncementEmailBroadcast entities.
type AnnouncementEmailBroadcastUpdate struct {
	config
	hooks    []Hook
	mutation *AnnouncementEmailBroadcastMutation
}

// Where appends a list predicates to the AnnouncementEmailBroadcastUpdate builder.
func (_u *AnnouncementEmailBroadcastUpdate) Where(ps ...predicate.AnnouncementEmailBroadcast) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAnnouncementID sets the "announcement_id" field.
func (_u *AnnouncementEmailBroadcastUpdate) SetAnnouncementID(v int64) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.ResetAnnouncementID()
	_u.mutation.SetAnnouncementID(v)
	return _u
}

// SetNillableAnnouncementID sets the "announcement_id" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdate) SetNillableAnnouncementID(v *int64) *AnnouncementEmailBroadcastUpdate {
	if v != nil {
		_u.SetAnnouncementID(*v)
	}
	return _u
}

// AddAnnouncementID adds value to the "announcement_id" field.
func (_u *AnnouncementEmailBroadcastUpdate) AddAnnouncementID(v int64) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.AddAnnouncementID(v)
	return _u
}

// SetSubject sets the "subject" field.
func (_u *AnnouncementEmailBroadcastUpdate) SetSubject(v string) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdate) SetNillableSubject(v *string) *AnnouncementEmailBroadcastUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetBodyHTML sets the "body_html" field.
func (_u *AnnouncementEmailBroadcastUpdate) SetBodyHTML(v string) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.SetBodyHTML(v)
	return _u
}

// SetNillableBodyHTML sets the "body_html" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdate) SetNillableBodyHTML(v *string) *AnnouncementEmailBroadcastUpdate {
	if v != nil {
		_u.SetBodyHTML(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AnnouncementEmailBroadcastUpdate) SetStatus(v string) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdate) SetNillableStatus(v *string) *AnnouncementEmailBroadcastUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalCount sets the "total_count" field.
func (_u *AnnouncementEmailBroadcastUpdate) SetTotalCount(v int) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.ResetTotalCount()
	_u.mutation.SetTotalCount(v)
	return _u
}

// SetNillableTotalCount sets the "total_count" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdate) SetNillableTotalCount(v *int) *AnnouncementEmailBroadcastUpdate {
	if v != nil {
		_u.SetTotalCount(*v)
	}
	return _u
}

// AddTotalCount adds value to the "total_count" field.
func (_u *AnnouncementEmailBroadcastUpdate) AddTotalCount(v int) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.AddTotalCount(v)
	return _u
}

// SetSentCount sets the "sent_count" field.
func (_u *AnnouncementEmailBroadcastUpdate) SetSentCount(v int) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.ResetSentCount()
	_u.mutation.SetSentCount(v)
	return _u
}

// SetNillableSentCount sets the "sent_count" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdate) SetNillableSentCount(v *int) *AnnouncementEmailBroadcastUpdate {
	if v != nil {
		_u.SetSentCount(*v)
	}
	return _u
}

// AddSentCount adds value to the "sent_count" field.
func (_u *AnnouncementEmailBroadcastUpdate) AddSentCount(v int) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.AddSentCount(v)
	return _u
}

// SetFailedCount sets the "failed_count" field.
func (_u *AnnouncementEmailBroadcastUpdate) SetFailedCount(v int) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.ResetFailedCount()
	_u.mutation.SetFailedCount(v)
	return _u
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdate) SetNillableFailedCount(v *int) *AnnouncementEmailBroadcastUpdate {
	if v != nil {
		_u.SetFailedCount(*v)
	}
	return _u
}

// AddFailedCount adds value to the "failed_count" field.
func (_u *AnnouncementEmailBroadcastUpdate) AddFailedCount(v int) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.AddFailedCount(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AnnouncementEmailBroadcastUpdate) SetCreatedBy(v int64) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdate) SetNillableCreatedBy(v *int64) *AnnouncementEmailBroadcastUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *AnnouncementEmailBroadcastUpdate) AddCreatedBy(v int64) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AnnouncementEmailBroadcastUpdate) ClearCreatedBy() *AnnouncementEmailBroadcastUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AnnouncementEmailBroadcastUpdate) SetCreatedAt(v time.Time) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdate) SetNillableCreatedAt(v *time.Time) *AnnouncementEmailBroadcastUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *AnnouncementEmailBroadcastUpdate) SetStartedAt(v time.Time) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdate) SetNillableStartedAt(v *time.Time) *AnnouncementEmailBroadcastUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *AnnouncementEmailBroadcastUpdate) ClearStartedAt() *AnnouncementEmailBroadcastUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *AnnouncementEmailBroadcastUpdate) SetCompletedAt(v time.Time) *AnnouncementEmailBroadcastUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdate) SetNillableCompletedAt(v *time.Time) *AnnouncementEmailBroadcastUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *AnnouncementEmailBroadcastUpdate) ClearCompletedAt() *AnnouncementEmailBroadcastUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the AnnouncementEmailBroadcastMutation object of the builder.
func (_u *AnnouncementEmailBroadcastUpdate) Mutation() *AnnouncementEmailBroadcastMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnnouncementEmailBroadcastUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementEmailBroadcastUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnnouncementEmailBroadcastUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementEmailBroadcastUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementEmailBroadcastUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := announcementemailbroadcast.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AnnouncementEmailBroadcast.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AnnouncementEmailBroadcastUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcementemailbroadcast.Table, announcementemailbroadcast.Columns, sqlgraph.NewFieldSpec(announcementemailbroadcast.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AnnouncementID(); ok {
		_spec.SetField(announcementemailbroadcast.FieldAnnouncementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAnnouncementID(); ok {
		_spec.AddField(announcementemailbroadcast.FieldAnnouncementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(announcementemailbroadcast.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.BodyHTML(); ok {
		_spec.SetField(announcementemailbroadcast.FieldBodyHTML, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(announcementemailbroadcast.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalCount(); ok {
		_spec.SetField(announcementemailbroadcast.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCount(); ok {
		_spec.AddField(announcementemailbroadcast.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SentCount(); ok {
		_spec.SetField(announcementemailbroadcast.FieldSentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSentCount(); ok {
		_spec.AddField(announcementemailbroadcast.FieldSentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedCount(); ok {
		_spec.SetField(announcementemailbroadcast.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedCount(); ok {
		_spec.AddField(announcementemailbroadcast.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(announcementemailbroadcast.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(announcementemailbroadcast.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(announcementemailbroadcast.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(announcementemailbroadcast.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(announcementemailbroadcast.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(announcementemailbroadcast.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(announcementemailbroadcast.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(announcementemailbroadcast.FieldCompletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcementemailbroadcast.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnnouncementEmailBroadcastUpdateOne is the builder for updating a single AnnouncementEmailBroadcast entity.
type AnnouncementEmailBroadcastUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnnouncementEmailBroadcastMutation
}

// SetAnnouncementID sets the "announcement_id" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetAnnouncementID(v int64) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.ResetAnnouncementID()
	_u.mutation.SetAnnouncementID(v)
	return _u
}

// SetNillableAnnouncementID sets the "announcement_id" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetNillableAnnouncementID(v *int64) *AnnouncementEmailBroadcastUpdateOne {
	if v != nil {
		_u.SetAnnouncementID(*v)
	}
	return _u
}

// AddAnnouncementID adds value to the "announcement_id" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) AddAnnouncementID(v int64) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.AddAnnouncementID(v)
	return _u
}

// SetSubject sets the "subject" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetSubject(v string) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetNillableSubject(v *string) *AnnouncementEmailBroadcastUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetBodyHTML sets the "body_html" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetBodyHTML(v string) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.SetBodyHTML(v)
	return _u
}

// SetNillableBodyHTML sets the "body_html" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetNillableBodyHTML(v *string) *AnnouncementEmailBroadcastUpdateOne {
	if v != nil {
		_u.SetBodyHTML(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetStatus(v string) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetNillableStatus(v *string) *AnnouncementEmailBroadcastUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalCount sets the "total_count" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetTotalCount(v int) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.ResetTotalCount()
	_u.mutation.SetTotalCount(v)
	return _u
}

// SetNillableTotalCount sets the "total_count" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetNillableTotalCount(v *int) *AnnouncementEmailBroadcastUpdateOne {
	if v != nil {
		_u.SetTotalCount(*v)
	}
	return _u
}

// AddTotalCount adds value to the "total_count" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) AddTotalCount(v int) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.AddTotalCount(v)
	return _u
}

// SetSentCount sets the "sent_count" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetSentCount(v int) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.ResetSentCount()
	_u.mutation.SetSentCount(v)
	return _u
}

// SetNillableSentCount sets the "sent_count" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetNillableSentCount(v *int) *AnnouncementEmailBroadcastUpdateOne {
	if v != nil {
		_u.SetSentCount(*v)
	}
	return _u
}

// AddSentCount adds value to the "sent_count" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) AddSentCount(v int) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.AddSentCount(v)
	return _u
}

// SetFailedCount sets the "failed_count" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetFailedCount(v int) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.ResetFailedCount()
	_u.mutation.SetFailedCount(v)
	return _u
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetNillableFailedCount(v *int) *AnnouncementEmailBroadcastUpdateOne {
	if v != nil {
		_u.SetFailedCount(*v)
	}
	return _u
}

// AddFailedCount adds value to the "failed_count" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) AddFailedCount(v int) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.AddFailedCount(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetCreatedBy(v int64) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetNillableCreatedBy(v *int64) *AnnouncementEmailBroadcastUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) AddCreatedBy(v int64) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) ClearCreatedBy() *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetCreatedAt(v time.Time) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetNillableCreatedAt(v *time.Time) *AnnouncementEmailBroadcastUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetStartedAt(v time.Time) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetNillableStartedAt(v *time.Time) *AnnouncementEmailBroadcastUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) ClearStartedAt() *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetCompletedAt(v time.Time) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *AnnouncementEmailBroadcastUpdateOne) SetNillableCompletedAt(v *time.Time) *AnnouncementEmailBroadcastUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *AnnouncementEmailBroadcastUpdateOne) ClearCompletedAt() *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the AnnouncementEmailBroadcastMutation object of the builder.
func (_u *AnnouncementEmailBroadcastUpdateOne) Mutation() *AnnouncementEmailBroadcastMutation {
	return _u.mutation
}

// Where appends a list predicates to the AnnouncementEmailBroadcastUpdate builder.
func (_u *AnnouncementEmailBroadcastUpdateOne) Where(ps ...predicate.AnnouncementEmailBroadcast) *AnnouncementEmailBroadcastUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnnouncementEmailBroadcastUpdateOne) Select(field string, fields ...string) *AnnouncementEmailBroadcastUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AnnouncementEmailBroadcast entity.
func (_u *AnnouncementEmailBroadcastUpdateOne) Save(ctx context.Context) (*AnnouncementEmailBroadcast, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementEmailBroadcastUpdateOne) SaveX(ctx context.Context) *AnnouncementEmailBroadcast {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnnouncementEmailBroadcastUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementEmailBroadcastUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementEmailBroadcastUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := announcementemailbroadcast.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AnnouncementEmailBroadcast.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AnnouncementEmailBroadcastUpdateOne) sqlSave(ctx context.Context) (_node *AnnouncementEmailBroadcast, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcementemailbroadcast.Table, announcementemailbroadcast.Columns, sqlgraph.NewFieldSpec(announcementemailbroadcast.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AnnouncementEmailBroadcast.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, announcementemailbroadcast.FieldID)
		for _, f := range fields {
			if !announcementemailbroadcast.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != announcementemailbroadcast.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AnnouncementID(); ok {
		_spec.SetField(announcementemailbroadcast.FieldAnnouncementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAnnouncementID(); ok {
		_spec.AddField(announcementemailbroadcast.FieldAnnouncementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(announcementemailbroadcast.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.BodyHTML(); ok {
		_spec.SetField(announcementemailbroadcast.FieldBodyHTML, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(announcementemailbroadcast.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalCount(); ok {
		_spec.SetField(announcementemailbroadcast.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCount(); ok {
		_spec.AddField(announcementemailbroadcast.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SentCount(); ok {
		_spec.SetField(announcementemailbroadcast.FieldSentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSentCount(); ok {
		_spec.AddField(announcementemailbroadcast.FieldSentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedCount(); ok {
		_spec.SetField(announcementemailbroadcast.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedCount(); ok {
		_spec.AddField(announcementemailbroadcast.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(announcementemailbroadcast.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(announcementemailbroadcast.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(announcementemailbroadcast.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(announcementemailbroadcast.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(announcementemailbroadcast.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(announcementemailbroadcast.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(announcementemailbroadcast.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(announcementemailbroadcast.FieldCompletedAt, field.TypeTime)
	}
	_node = &AnnouncementEmailBroadcast{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcementemailbroadcast.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
