// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"encoding/json/jsontext"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/conversationexportjob"
)

// ConversationExportJob is the model entity for the ConversationExportJob schema.
type ConversationExportJob struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Filters holds the value of the "filters" field.
	Filters map[string]jsontext.Value `json:"filters,omitempty"`
	// Format holds the value of the "format" field.
	Format string `json:"format,omitempty"`
	// Encoding holds the value of the "encoding" field.
	Encoding string `json:"encoding,omitempty"`
	// SessionCount holds the value of the "session_count" field.
	SessionCount int64 `json:"session_count,omitempty"`
	// TurnCount holds the value of the "turn_count" field.
	TurnCount int64 `json:"turn_count,omitempty"`
	// FileSize holds the value of the "file_size" field.
	FileSize int64 `json:"file_size,omitempty"`
	// S3Key holds the value of the "s3_key" field.
	S3Key *string `json:"s3_key,omitempty"`
	// DownloadURLExpiresAt holds the value of the "download_url_expires_at" field.
	DownloadURLExpiresAt *time.Time `json:"download_url_expires_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ConversationExportJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case conversationexportjob.FieldFilters:
			values[i] = new([]byte)
		case conversationexportjob.FieldID, conversationexportjob.FieldSessionCount, conversationexportjob.FieldTurnCount, conversationexportjob.FieldFileSize, conversationexportjob.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case conversationexportjob.FieldStatus, conversationexportjob.FieldFormat, conversationexportjob.FieldEncoding, conversationexportjob.FieldS3Key, conversationexportjob.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case conversationexportjob.FieldDownloadURLExpiresAt, conversationexportjob.FieldExpiresAt, conversationexportjob.FieldCreatedAt, conversationexportjob.FieldUpdatedAt, conversationexportjob.FieldStartedAt, conversationexportjob.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ConversationExportJob fields.
func (_m *ConversationExportJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case conversationexportjob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case conversationexportjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case conversationexportjob.FieldFilters:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field filters", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Filters); err != nil {
					return fmt.Errorf("unmarshal field filters: %w", err)
				}
			}
		case conversationexportjob.FieldFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field format", values[i])
			} else if value.Valid {
				_m.Format = value.String
			}
		case conversationexportjob.FieldEncoding:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encoding", values[i])
			} else if value.Valid {
				_m.Encoding = value.String
			}
		case conversationexportjob.FieldSessionCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field session_count", values[i])
			} else if value.Valid {
				_m.SessionCount = value.Int64
			}
		case conversationexportjob.FieldTurnCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field turn_count", values[i])
			} else if value.Valid {
				_m.TurnCount = value.Int64
			}
		case conversationexportjob.FieldFileSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size", values[i])
			} else if value.Valid {
				_m.FileSize = value.Int64
			}
		case conversationexportjob.FieldS3Key:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field s3_key", values[i])
			} else if value.Valid {
				_m.S3Key = new(string)
				*_m.S3Key = value.String
			}
		case conversationexportjob.FieldDownloadURLExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field download_url_expires_at", values[i])
			} else if value.Valid {
				_m.DownloadURLExpiresAt = new(time.Time)
				*_m.DownloadURLExpiresAt = value.Time
			}
		case conversationexportjob.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case conversationexportjob.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case conversationexportjob.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case conversationexportjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case conversationexportjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case conversationexportjob.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case conversationexportjob.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ConversationExportJob.
// This includes values selected through modifiers, order, etc.
func (_m *ConversationExportJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ConversationExportJob.
// Note that you need to call ConversationExportJob.Unwrap() before calling this method if this ConversationExportJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ConversationExportJob) Update() *ConversationExportJobUpdateOne {
	return NewConversationExportJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ConversationExportJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ConversationExportJob) Unwrap() *ConversationExportJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ConversationExportJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ConversationExportJob) String() string {
	var builder strings.Builder
	builder.WriteString("ConversationExportJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("filters=")
	builder.WriteString(fmt.Sprintf("%v", _m.Filters))
	builder.WriteString(", ")
	builder.WriteString("format=")
	builder.WriteString(_m.Format)
	builder.WriteString(", ")
	builder.WriteString("encoding=")
	builder.WriteString(_m.Encoding)
	builder.WriteString(", ")
	builder.WriteString("session_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionCount))
	builder.WriteString(", ")
	builder.WriteString("turn_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TurnCount))
	builder.WriteString(", ")
	builder.WriteString("file_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileSize))
	builder.WriteString(", ")
	if v := _m.S3Key; v != nil {
		builder.WriteString("s3_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DownloadURLExpiresAt; v != nil {
		builder.WriteString("download_url_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ConversationExportJobs is a parsable slice of ConversationExportJob.
type ConversationExportJobs []*ConversationExportJob
