// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversationturn"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ConversationTurnUpdate is the builder for updating ConversationTurn entities.
type ConversationTurnUpdate struct {
	config
	hooks    []Hook
	mutation *ConversationTurnMutation
}

// Where appends a list predicates to the ConversationTurnUpdate builder.
func (_u *ConversationTurnUpdate) Where(ps ...predicate.ConversationTurn) *ConversationTurnUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *ConversationTurnUpdate) SetSessionID(v string) *ConversationTurnUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableSessionID(v *string) *ConversationTurnUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *ConversationTurnUpdate) SetRequestID(v string) *ConversationTurnUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableRequestID(v *string) *ConversationTurnUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (_u *ConversationTurnUpdate) SetUpstreamRequestID(v string) *ConversationTurnUpdate {
	_u.mutation.SetUpstreamRequestID(v)
	return _u
}

// SetNillableUpstreamRequestID sets the "upstream_request_id" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableUpstreamRequestID(v *string) *ConversationTurnUpdate {
	if v != nil {
		_u.SetUpstreamRequestID(*v)
	}
	return _u
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (_u *ConversationTurnUpdate) ClearUpstreamRequestID() *ConversationTurnUpdate {
	_u.mutation.ClearUpstreamRequestID()
	return _u
}

// SetClientRequestID sets the "client_request_id" field.
func (_u *ConversationTurnUpdate) SetClientRequestID(v string) *ConversationTurnUpdate {
	_u.mutation.SetClientRequestID(v)
	return _u
}

// SetNillableClientRequestID sets the "client_request_id" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableClientRequestID(v *string) *ConversationTurnUpdate {
	if v != nil {
		_u.SetClientRequestID(*v)
	}
	return _u
}

// ClearClientRequestID clears the value of the "client_request_id" field.
func (_u *ConversationTurnUpdate) ClearClientRequestID() *ConversationTurnUpdate {
	_u.mutation.ClearClientRequestID()
	return _u
}

// SetTurnIndex sets the "turn_index" field.
func (_u *ConversationTurnUpdate) SetTurnIndex(v int) *ConversationTurnUpdate {
	_u.mutation.ResetTurnIndex()
	_u.mutation.SetTurnIndex(v)
	return _u
}

// SetNillableTurnIndex sets the "turn_index" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableTurnIndex(v *int) *ConversationTurnUpdate {
	if v != nil {
		_u.SetTurnIndex(*v)
	}
	return _u
}

// AddTurnIndex adds value to the "turn_index" field.
func (_u *ConversationTurnUpdate) AddTurnIndex(v int) *ConversationTurnUpdate {
	_u.mutation.AddTurnIndex(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ConversationTurnUpdate) SetProvider(v string) *ConversationTurnUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableProvider(v *string) *ConversationTurnUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *ConversationTurnUpdate) SetModel(v string) *ConversationTurnUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableModel(v *string) *ConversationTurnUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRequestPath sets the "request_path" field.
func (_u *ConversationTurnUpdate) SetRequestPath(v string) *ConversationTurnUpdate {
	_u.mutation.SetRequestPath(v)
	return _u
}

// SetNillableRequestPath sets the "request_path" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableRequestPath(v *string) *ConversationTurnUpdate {
	if v != nil {
		_u.SetRequestPath(*v)
	}
	return _u
}

// SetRequestMessages sets the "request_messages" field.
func (_u *ConversationTurnUpdate) SetRequestMessages(v []jsontext.Value) *ConversationTurnUpdate {
	_u.mutation.SetRequestMessages(v)
	return _u
}

// AppendRequestMessages appends value to the "request_messages" field.
func (_u *ConversationTurnUpdate) AppendRequestMessages(v []jsontext.Value) *ConversationTurnUpdate {
	_u.mutation.AppendRequestMessages(v)
	return _u
}

// ClearRequestMessages clears the value of the "request_messages" field.
func (_u *ConversationTurnUpdate) ClearRequestMessages() *ConversationTurnUpdate {
	_u.mutation.ClearRequestMessages()
	return _u
}

// SetResponseMessages sets the "response_messages" field.
func (_u *ConversationTurnUpdate) SetResponseMessages(v []jsontext.Value) *ConversationTurnUpdate {
	_u.mutation.SetResponseMessages(v)
	return _u
}

// AppendResponseMessages appends value to the "response_messages" field.
func (_u *ConversationTurnUpdate) AppendResponseMessages(v []jsontext.Value) *ConversationTurnUpdate {
	_u.mutation.AppendResponseMessages(v)
	return _u
}

// ClearResponseMessages clears the value of the "response_messages" field.
func (_u *ConversationTurnUpdate) ClearResponseMessages() *ConversationTurnUpdate {
	_u.mutation.ClearResponseMessages()
	return _u
}

// SetTools sets the "tools" field.
func (_u *ConversationTurnUpdate) SetTools(v []jsontext.Value) *ConversationTurnUpdate {
	_u.mutation.SetTools(v)
	return _u
}

// AppendTools appends value to the "tools" field.
func (_u *ConversationTurnUpdate) AppendTools(v []jsontext.Value) *ConversationTurnUpdate {
	_u.mutation.AppendTools(v)
	return _u
}

// ClearTools clears the value of the "tools" field.
func (_u *ConversationTurnUpdate) ClearTools() *ConversationTurnUpdate {
	_u.mutation.ClearTools()
	return _u
}

// SetUsage sets the "usage" field.
func (_u *ConversationTurnUpdate) SetUsage(v map[string]interface{}) *ConversationTurnUpdate {
	_u.mutation.SetUsage(v)
	return _u
}

// ClearUsage clears the value of the "usage" field.
func (_u *ConversationTurnUpdate) ClearUsage() *ConversationTurnUpdate {
	_u.mutation.ClearUsage()
	return _u
}

// SetMeta sets the "meta" field.
func (_u *ConversationTurnUpdate) SetMeta(v map[string]interface{}) *ConversationTurnUpdate {
	_u.mutation.SetMeta(v)
	return _u
}

// ClearMeta clears the value of the "meta" field.
func (_u *ConversationTurnUpdate) ClearMeta() *ConversationTurnUpdate {
	_u.mutation.ClearMeta()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *ConversationTurnUpdate) SetInputTokens(v int64) *ConversationTurnUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableInputTokens(v *int64) *ConversationTurnUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *ConversationTurnUpdate) AddInputTokens(v int64) *ConversationTurnUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *ConversationTurnUpdate) SetOutputTokens(v int64) *ConversationTurnUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableOutputTokens(v *int64) *ConversationTurnUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *ConversationTurnUpdate) AddOutputTokens(v int64) *ConversationTurnUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *ConversationTurnUpdate) SetTotalTokens(v int64) *ConversationTurnUpdate {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableTotalTokens(v *int64) *ConversationTurnUpdate {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *ConversationTurnUpdate) AddTotalTokens(v int64) *ConversationTurnUpdate {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *ConversationTurnUpdate) SetActualCost(v float64) *ConversationTurnUpdate {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableActualCost(v *float64) *ConversationTurnUpdate {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *ConversationTurnUpdate) AddActualCost(v float64) *ConversationTurnUpdate {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetStream sets the "stream" field.
func (_u *ConversationTurnUpdate) SetStream(v bool) *ConversationTurnUpdate {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableStream(v *bool) *ConversationTurnUpdate {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetClientDisconnect sets the "client_disconnect" field.
func (_u *ConversationTurnUpdate) SetClientDisconnect(v bool) *ConversationTurnUpdate {
	_u.mutation.SetClientDisconnect(v)
	return _u
}

// SetNillableClientDisconnect sets the "client_disconnect" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableClientDisconnect(v *bool) *ConversationTurnUpdate {
	if v != nil {
		_u.SetClientDisconnect(*v)
	}
	return _u
}

// SetTruncated sets the "truncated" field.
func (_u *ConversationTurnUpdate) SetTruncated(v bool) *ConversationTurnUpdate {
	_u.mutation.SetTruncated(v)
	return _u
}

// SetNillableTruncated sets the "truncated" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableTruncated(v *bool) *ConversationTurnUpdate {
	if v != nil {
		_u.SetTruncated(*v)
	}
	return _u
}

// SetQualityStatus sets the "quality_status" field.
func (_u *ConversationTurnUpdate) SetQualityStatus(v string) *ConversationTurnUpdate {
	_u.mutation.SetQualityStatus(v)
	return _u
}

// SetNillableQualityStatus sets the "quality_status" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableQualityStatus(v *string) *ConversationTurnUpdate {
	if v != nil {
		_u.SetQualityStatus(*v)
	}
	return _u
}

// SetQualityErrors sets the "quality_errors" field.
func (_u *ConversationTurnUpdate) SetQualityErrors(v []jsontext.Value) *ConversationTurnUpdate {
	_u.mutation.SetQualityErrors(v)
	return _u
}

// AppendQualityErrors appends value to the "quality_errors" field.
func (_u *ConversationTurnUpdate) AppendQualityErrors(v []jsontext.Value) *ConversationTurnUpdate {
	_u.mutation.AppendQualityErrors(v)
	return _u
}

// ClearQualityErrors clears the value of the "quality_errors" field.
func (_u *ConversationTurnUpdate) ClearQualityErrors() *ConversationTurnUpdate {
	_u.mutation.ClearQualityErrors()
	return _u
}

// SetExportable sets the "exportable" field.
func (_u *ConversationTurnUpdate) SetExportable(v bool) *ConversationTurnUpdate {
	_u.mutation.SetExportable(v)
	return _u
}

// SetNillableExportable sets the "exportable" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableExportable(v *bool) *ConversationTurnUpdate {
	if v != nil {
		_u.SetExportable(*v)
	}
	return _u
}

// SetParseStatus sets the "parse_status" field.
func (_u *ConversationTurnUpdate) SetParseStatus(v string) *ConversationTurnUpdate {
	_u.mutation.SetParseStatus(v)
	return _u
}

// SetNillableParseStatus sets the "parse_status" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableParseStatus(v *string) *ConversationTurnUpdate {
	if v != nil {
		_u.SetParseStatus(*v)
	}
	return _u
}

// SetParseError sets the "parse_error" field.
func (_u *ConversationTurnUpdate) SetParseError(v string) *ConversationTurnUpdate {
	_u.mutation.SetParseError(v)
	return _u
}

// SetNillableParseError sets the "parse_error" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableParseError(v *string) *ConversationTurnUpdate {
	if v != nil {
		_u.SetParseError(*v)
	}
	return _u
}

// ClearParseError clears the value of the "parse_error" field.
func (_u *ConversationTurnUpdate) ClearParseError() *ConversationTurnUpdate {
	_u.mutation.ClearParseError()
	return _u
}

// SetDedupeHash sets the "dedupe_hash" field.
func (_u *ConversationTurnUpdate) SetDedupeHash(v string) *ConversationTurnUpdate {
	_u.mutation.SetDedupeHash(v)
	return _u
}

// SetNillableDedupeHash sets the "dedupe_hash" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableDedupeHash(v *string) *ConversationTurnUpdate {
	if v != nil {
		_u.SetDedupeHash(*v)
	}
	return _u
}

// SetRawArchiveKey sets the "raw_archive_key" field.
func (_u *ConversationTurnUpdate) SetRawArchiveKey(v string) *ConversationTurnUpdate {
	_u.mutation.SetRawArchiveKey(v)
	return _u
}

// SetNillableRawArchiveKey sets the "raw_archive_key" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableRawArchiveKey(v *string) *ConversationTurnUpdate {
	if v != nil {
		_u.SetRawArchiveKey(*v)
	}
	return _u
}

// ClearRawArchiveKey clears the value of the "raw_archive_key" field.
func (_u *ConversationTurnUpdate) ClearRawArchiveKey() *ConversationTurnUpdate {
	_u.mutation.ClearRawArchiveKey()
	return _u
}

// SetPayloadPreview sets the "payload_preview" field.
func (_u *ConversationTurnUpdate) SetPayloadPreview(v string) *ConversationTurnUpdate {
	_u.mutation.SetPayloadPreview(v)
	return _u
}

// SetNillablePayloadPreview sets the "payload_preview" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillablePayloadPreview(v *string) *ConversationTurnUpdate {
	if v != nil {
		_u.SetPayloadPreview(*v)
	}
	return _u
}

// ClearPayloadPreview clears the value of the "payload_preview" field.
func (_u *ConversationTurnUpdate) ClearPayloadPreview() *ConversationTurnUpdate {
	_u.mutation.ClearPayloadPreview()
	return _u
}

// SetPayloadCompressed sets the "payload_compressed" field.
func (_u *ConversationTurnUpdate) SetPayloadCompressed(v []byte) *ConversationTurnUpdate {
	_u.mutation.SetPayloadCompressed(v)
	return _u
}

// ClearPayloadCompressed clears the value of the "payload_compressed" field.
func (_u *ConversationTurnUpdate) ClearPayloadCompressed() *ConversationTurnUpdate {
	_u.mutation.ClearPayloadCompressed()
	return _u
}

// SetRetentionUntil sets the "retention_until" field.
func (_u *ConversationTurnUpdate) SetRetentionUntil(v time.Time) *ConversationTurnUpdate {
	_u.mutation.SetRetentionUntil(v)
	return _u
}

// SetNillableRetentionUntil sets the "retention_until" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableRetentionUntil(v *time.Time) *ConversationTurnUpdate {
	if v != nil {
		_u.SetRetentionUntil(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ConversationTurnUpdate) SetCreatedAt(v time.Time) *ConversationTurnUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ConversationTurnUpdate) SetNillableCreatedAt(v *time.Time) *ConversationTurnUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the ConversationTurnMutation object of the builder.
func (_u *ConversationTurnUpdate) Mutation() *ConversationTurnMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConversationTurnUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationTurnUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConversationTurnUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationTurnUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationTurnUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := conversationturn.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := conversationturn.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamRequestID(); ok {
		if err := conversationturn.UpstreamRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_request_id", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.upstream_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientRequestID(); ok {
		if err := conversationturn.ClientRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "client_request_id", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.client_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := conversationturn.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := conversationturn.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestPath(); ok {
		if err := conversationturn.RequestPathValidator(v); err != nil {
			return &ValidationError{Name: "request_path", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.request_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QualityStatus(); ok {
		if err := conversationturn.QualityStatusValidator(v); err != nil {
			return &ValidationError{Name: "quality_status", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.quality_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ParseStatus(); ok {
		if err := conversationturn.ParseStatusValidator(v); err != nil {
			return &ValidationError{Name: "parse_status", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.parse_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ParseError(); ok {
		if err := conversationturn.ParseErrorValidator(v); err != nil {
			return &ValidationError{Name: "parse_error", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.parse_error": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DedupeHash(); ok {
		if err := conversationturn.DedupeHashValidator(v); err != nil {
			return &ValidationError{Name: "dedupe_hash", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.dedupe_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RawArchiveKey(); ok {
		if err := conversationturn.RawArchiveKeyValidator(v); err != nil {
			return &ValidationError{Name: "raw_archive_key", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.raw_archive_key": %w`, err)}
		}
	}
	return nil
}

func (_u *ConversationTurnUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversationturn.Table, conversationturn.Columns, sqlgraph.NewFieldSpec(conversationturn.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(conversationturn.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(conversationturn.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamRequestID(); ok {
		_spec.SetField(conversationturn.FieldUpstreamRequestID, field.TypeString, value)
	}
	if _u.mutation.UpstreamRequestIDCleared() {
		_spec.ClearField(conversationturn.FieldUpstreamRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.ClientRequestID(); ok {
		_spec.SetField(conversationturn.FieldClientRequestID, field.TypeString, value)
	}
	if _u.mutation.ClientRequestIDCleared() {
		_spec.ClearField(conversationturn.FieldClientRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.TurnIndex(); ok {
		_spec.SetField(conversationturn.FieldTurnIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTurnIndex(); ok {
		_spec.AddField(conversationturn.FieldTurnIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(conversationturn.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(conversationturn.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestPath(); ok {
		_spec.SetField(conversationturn.FieldRequestPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestMessages(); ok {
		_spec.SetField(conversationturn.FieldRequestMessages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequestMessages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, conversationturn.FieldRequestMessages, value)
		})
	}
	if _u.mutation.RequestMessagesCleared() {
		_spec.ClearField(conversationturn.FieldRequestMessages, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResponseMessages(); ok {
		_spec.SetField(conversationturn.FieldResponseMessages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResponseMessages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, conversationturn.FieldResponseMessages, value)
		})
	}
	if _u.mutation.ResponseMessagesCleared() {
		_spec.ClearField(conversationturn.FieldResponseMessages, field.TypeJSON)
	}
	if value, ok := _u.mutation.Tools(); ok {
		_spec.SetField(conversationturn.FieldTools, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTools(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, conversationturn.FieldTools, value)
		})
	}
	if _u.mutation.ToolsCleared() {
		_spec.ClearField(conversationturn.FieldTools, field.TypeJSON)
	}
	if value, ok := _u.mutation.Usage(); ok {
		_spec.SetField(conversationturn.FieldUsage, field.TypeJSON, value)
	}
	if _u.mutation.UsageCleared() {
		_spec.ClearField(conversationturn.FieldUsage, field.TypeJSON)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(conversationturn.FieldMeta, field.TypeJSON, value)
	}
	if _u.mutation.MetaCleared() {
		_spec.ClearField(conversationturn.FieldMeta, field.TypeJSON)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(conversationturn.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(conversationturn.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(conversationturn.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(conversationturn.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(conversationturn.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(conversationturn.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(conversationturn.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(conversationturn.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(conversationturn.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ClientDisconnect(); ok {
		_spec.SetField(conversationturn.FieldClientDisconnect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Truncated(); ok {
		_spec.SetField(conversationturn.FieldTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QualityStatus(); ok {
		_spec.SetField(conversationturn.FieldQualityStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.QualityErrors(); ok {
		_spec.SetField(conversationturn.FieldQualityErrors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedQualityErrors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, conversationturn.FieldQualityErrors, value)
		})
	}
	if _u.mutation.QualityErrorsCleared() {
		_spec.ClearField(conversationturn.FieldQualityErrors, field.TypeJSON)
	}
	if value, ok := _u.mutation.Exportable(); ok {
		_spec.SetField(conversationturn.FieldExportable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ParseStatus(); ok {
		_spec.SetField(conversationturn.FieldParseStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParseError(); ok {
		_spec.SetField(conversationturn.FieldParseError, field.TypeString, value)
	}
	if _u.mutation.ParseErrorCleared() {
		_spec.ClearField(conversationturn.FieldParseError, field.TypeString)
	}
	if value, ok := _u.mutation.DedupeHash(); ok {
		_spec.SetField(conversationturn.FieldDedupeHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.RawArchiveKey(); ok {
		_spec.SetField(conversationturn.FieldRawArchiveKey, field.TypeString, value)
	}
	if _u.mutation.RawArchiveKeyCleared() {
		_spec.ClearField(conversationturn.FieldRawArchiveKey, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadPreview(); ok {
		_spec.SetField(conversationturn.FieldPayloadPreview, field.TypeString, value)
	}
	if _u.mutation.PayloadPreviewCleared() {
		_spec.ClearField(conversationturn.FieldPayloadPreview, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadCompressed(); ok {
		_spec.SetField(conversationturn.FieldPayloadCompressed, field.TypeBytes, value)
	}
	if _u.mutation.PayloadCompressedCleared() {
		_spec.ClearField(conversationturn.FieldPayloadCompressed, field.TypeBytes)
	}
	if value, ok := _u.mutation.RetentionUntil(); ok {
		_spec.SetField(conversationturn.FieldRetentionUntil, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(conversationturn.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversationturn.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConversationTurnUpdateOne is the builder for updating a single ConversationTurn entity.
type ConversationTurnUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConversationTurnMutation
}

// SetSessionID sets the "session_id" field.
func (_u *ConversationTurnUpdateOne) SetSessionID(v string) *ConversationTurnUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableSessionID(v *string) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *ConversationTurnUpdateOne) SetRequestID(v string) *ConversationTurnUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableRequestID(v *string) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (_u *ConversationTurnUpdateOne) SetUpstreamRequestID(v string) *ConversationTurnUpdateOne {
	_u.mutation.SetUpstreamRequestID(v)
	return _u
}

// SetNillableUpstreamRequestID sets the "upstream_request_id" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableUpstreamRequestID(v *string) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetUpstreamRequestID(*v)
	}
	return _u
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (_u *ConversationTurnUpdateOne) ClearUpstreamRequestID() *ConversationTurnUpdateOne {
	_u.mutation.ClearUpstreamRequestID()
	return _u
}

// SetClientRequestID sets the "client_request_id" field.
func (_u *ConversationTurnUpdateOne) SetClientRequestID(v string) *ConversationTurnUpdateOne {
	_u.mutation.SetClientRequestID(v)
	return _u
}

// SetNillableClientRequestID sets the "client_request_id" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableClientRequestID(v *string) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetClientRequestID(*v)
	}
	return _u
}

// ClearClientRequestID clears the value of the "client_request_id" field.
func (_u *ConversationTurnUpdateOne) ClearClientRequestID() *ConversationTurnUpdateOne {
	_u.mutation.ClearClientRequestID()
	return _u
}

// SetTurnIndex sets the "turn_index" field.
func (_u *ConversationTurnUpdateOne) SetTurnIndex(v int) *ConversationTurnUpdateOne {
	_u.mutation.ResetTurnIndex()
	_u.mutation.SetTurnIndex(v)
	return _u
}

// SetNillableTurnIndex sets the "turn_index" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableTurnIndex(v *int) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetTurnIndex(*v)
	}
	return _u
}

// AddTurnIndex adds value to the "turn_index" field.
func (_u *ConversationTurnUpdateOne) AddTurnIndex(v int) *ConversationTurnUpdateOne {
	_u.mutation.AddTurnIndex(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ConversationTurnUpdateOne) SetProvider(v string) *ConversationTurnUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableProvider(v *string) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *ConversationTurnUpdateOne) SetModel(v string) *ConversationTurnUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableModel(v *string) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRequestPath sets the "request_path" field.
func (_u *ConversationTurnUpdateOne) SetRequestPath(v string) *ConversationTurnUpdateOne {
	_u.mutation.SetRequestPath(v)
	return _u
}

// SetNillableRequestPath sets the "request_path" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableRequestPath(v *string) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetRequestPath(*v)
	}
	return _u
}

// SetRequestMessages sets the "request_messages" field.
func (_u *ConversationTurnUpdateOne) SetRequestMessages(v []jsontext.Value) *ConversationTurnUpdateOne {
	_u.mutation.SetRequestMessages(v)
	return _u
}

// AppendRequestMessages appends value to the "request_messages" field.
func (_u *ConversationTurnUpdateOne) AppendRequestMessages(v []jsontext.Value) *ConversationTurnUpdateOne {
	_u.mutation.AppendRequestMessages(v)
	return _u
}

// ClearRequestMessages clears the value of the "request_messages" field.
func (_u *ConversationTurnUpdateOne) ClearRequestMessages() *ConversationTurnUpdateOne {
	_u.mutation.ClearRequestMessages()
	return _u
}

// SetResponseMessages sets the "response_messages" field.
func (_u *ConversationTurnUpdateOne) SetResponseMessages(v []jsontext.Value) *ConversationTurnUpdateOne {
	_u.mutation.SetResponseMessages(v)
	return _u
}

// AppendResponseMessages appends value to the "response_messages" field.
func (_u *ConversationTurnUpdateOne) AppendResponseMessages(v []jsontext.Value) *ConversationTurnUpdateOne {
	_u.mutation.AppendResponseMessages(v)
	return _u
}

// ClearResponseMessages clears the value of the "response_messages" field.
func (_u *ConversationTurnUpdateOne) ClearResponseMessages() *ConversationTurnUpdateOne {
	_u.mutation.ClearResponseMessages()
	return _u
}

// SetTools sets the "tools" field.
func (_u *ConversationTurnUpdateOne) SetTools(v []jsontext.Value) *ConversationTurnUpdateOne {
	_u.mutation.SetTools(v)
	return _u
}

// AppendTools appends value to the "tools" field.
func (_u *ConversationTurnUpdateOne) AppendTools(v []jsontext.Value) *ConversationTurnUpdateOne {
	_u.mutation.AppendTools(v)
	return _u
}

// ClearTools clears the value of the "tools" field.
func (_u *ConversationTurnUpdateOne) ClearTools() *ConversationTurnUpdateOne {
	_u.mutation.ClearTools()
	return _u
}

// SetUsage sets the "usage" field.
func (_u *ConversationTurnUpdateOne) SetUsage(v map[string]interface{}) *ConversationTurnUpdateOne {
	_u.mutation.SetUsage(v)
	return _u
}

// ClearUsage clears the value of the "usage" field.
func (_u *ConversationTurnUpdateOne) ClearUsage() *ConversationTurnUpdateOne {
	_u.mutation.ClearUsage()
	return _u
}

// SetMeta sets the "meta" field.
func (_u *ConversationTurnUpdateOne) SetMeta(v map[string]interface{}) *ConversationTurnUpdateOne {
	_u.mutation.SetMeta(v)
	return _u
}

// ClearMeta clears the value of the "meta" field.
func (_u *ConversationTurnUpdateOne) ClearMeta() *ConversationTurnUpdateOne {
	_u.mutation.ClearMeta()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *ConversationTurnUpdateOne) SetInputTokens(v int64) *ConversationTurnUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableInputTokens(v *int64) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *ConversationTurnUpdateOne) AddInputTokens(v int64) *ConversationTurnUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *ConversationTurnUpdateOne) SetOutputTokens(v int64) *ConversationTurnUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableOutputTokens(v *int64) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *ConversationTurnUpdateOne) AddOutputTokens(v int64) *ConversationTurnUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *ConversationTurnUpdateOne) SetTotalTokens(v int64) *ConversationTurnUpdateOne {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableTotalTokens(v *int64) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *ConversationTurnUpdateOne) AddTotalTokens(v int64) *ConversationTurnUpdateOne {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *ConversationTurnUpdateOne) SetActualCost(v float64) *ConversationTurnUpdateOne {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableActualCost(v *float64) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *ConversationTurnUpdateOne) AddActualCost(v float64) *ConversationTurnUpdateOne {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetStream sets the "stream" field.
func (_u *ConversationTurnUpdateOne) SetStream(v bool) *ConversationTurnUpdateOne {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableStream(v *bool) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetClientDisconnect sets the "client_disconnect" field.
func (_u *ConversationTurnUpdateOne) SetClientDisconnect(v bool) *ConversationTurnUpdateOne {
	_u.mutation.SetClientDisconnect(v)
	return _u
}

// SetNillableClientDisconnect sets the "client_disconnect" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableClientDisconnect(v *bool) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetClientDisconnect(*v)
	}
	return _u
}

// SetTruncated sets the "truncated" field.
func (_u *ConversationTurnUpdateOne) SetTruncated(v bool) *ConversationTurnUpdateOne {
	_u.mutation.SetTruncated(v)
	return _u
}

// SetNillableTruncated sets the "truncated" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableTruncated(v *bool) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetTruncated(*v)
	}
	return _u
}

// SetQualityStatus sets the "quality_status" field.
func (_u *ConversationTurnUpdateOne) SetQualityStatus(v string) *ConversationTurnUpdateOne {
	_u.mutation.SetQualityStatus(v)
	return _u
}

// SetNillableQualityStatus sets the "quality_status" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableQualityStatus(v *string) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetQualityStatus(*v)
	}
	return _u
}

// SetQualityErrors sets the "quality_errors" field.
func (_u *ConversationTurnUpdateOne) SetQualityErrors(v []jsontext.Value) *ConversationTurnUpdateOne {
	_u.mutation.SetQualityErrors(v)
	return _u
}

// AppendQualityErrors appends value to the "quality_errors" field.
func (_u *ConversationTurnUpdateOne) AppendQualityErrors(v []jsontext.Value) *ConversationTurnUpdateOne {
	_u.mutation.AppendQualityErrors(v)
	return _u
}

// ClearQualityErrors clears the value of the "quality_errors" field.
func (_u *ConversationTurnUpdateOne) ClearQualityErrors() *ConversationTurnUpdateOne {
	_u.mutation.ClearQualityErrors()
	return _u
}

// SetExportable sets the "exportable" field.
func (_u *ConversationTurnUpdateOne) SetExportable(v bool) *ConversationTurnUpdateOne {
	_u.mutation.SetExportable(v)
	return _u
}

// SetNillableExportable sets the "exportable" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableExportable(v *bool) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetExportable(*v)
	}
	return _u
}

// SetParseStatus sets the "parse_status" field.
func (_u *ConversationTurnUpdateOne) SetParseStatus(v string) *ConversationTurnUpdateOne {
	_u.mutation.SetParseStatus(v)
	return _u
}

// SetNillableParseStatus sets the "parse_status" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableParseStatus(v *string) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetParseStatus(*v)
	}
	return _u
}

// SetParseError sets the "parse_error" field.
func (_u *ConversationTurnUpdateOne) SetParseError(v string) *ConversationTurnUpdateOne {
	_u.mutation.SetParseError(v)
	return _u
}

// SetNillableParseError sets the "parse_error" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableParseError(v *string) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetParseError(*v)
	}
	return _u
}

// ClearParseError clears the value of the "parse_error" field.
func (_u *ConversationTurnUpdateOne) ClearParseError() *ConversationTurnUpdateOne {
	_u.mutation.ClearParseError()
	return _u
}

// SetDedupeHash sets the "dedupe_hash" field.
func (_u *ConversationTurnUpdateOne) SetDedupeHash(v string) *ConversationTurnUpdateOne {
	_u.mutation.SetDedupeHash(v)
	return _u
}

// SetNillableDedupeHash sets the "dedupe_hash" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableDedupeHash(v *string) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetDedupeHash(*v)
	}
	return _u
}

// SetRawArchiveKey sets the "raw_archive_key" field.
func (_u *ConversationTurnUpdateOne) SetRawArchiveKey(v string) *ConversationTurnUpdateOne {
	_u.mutation.SetRawArchiveKey(v)
	return _u
}

// SetNillableRawArchiveKey sets the "raw_archive_key" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableRawArchiveKey(v *string) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetRawArchiveKey(*v)
	}
	return _u
}

// ClearRawArchiveKey clears the value of the "raw_archive_key" field.
func (_u *ConversationTurnUpdateOne) ClearRawArchiveKey() *ConversationTurnUpdateOne {
	_u.mutation.ClearRawArchiveKey()
	return _u
}

// SetPayloadPreview sets the "payload_preview" field.
func (_u *ConversationTurnUpdateOne) SetPayloadPreview(v string) *ConversationTurnUpdateOne {
	_u.mutation.SetPayloadPreview(v)
	return _u
}

// SetNillablePayloadPreview sets the "payload_preview" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillablePayloadPreview(v *string) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetPayloadPreview(*v)
	}
	return _u
}

// ClearPayloadPreview clears the value of the "payload_preview" field.
func (_u *ConversationTurnUpdateOne) ClearPayloadPreview() *ConversationTurnUpdateOne {
	_u.mutation.ClearPayloadPreview()
	return _u
}

// SetPayloadCompressed sets the "payload_compressed" field.
func (_u *ConversationTurnUpdateOne) SetPayloadCompressed(v []byte) *ConversationTurnUpdateOne {
	_u.mutation.SetPayloadCompressed(v)
	return _u
}

// ClearPayloadCompressed clears the value of the "payload_compressed" field.
func (_u *ConversationTurnUpdateOne) ClearPayloadCompressed() *ConversationTurnUpdateOne {
	_u.mutation.ClearPayloadCompressed()
	return _u
}

// SetRetentionUntil sets the "retention_until" field.
func (_u *ConversationTurnUpdateOne) SetRetentionUntil(v time.Time) *ConversationTurnUpdateOne {
	_u.mutation.SetRetentionUntil(v)
	return _u
}

// SetNillableRetentionUntil sets the "retention_until" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableRetentionUntil(v *time.Time) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetRetentionUntil(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ConversationTurnUpdateOne) SetCreatedAt(v time.Time) *ConversationTurnUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ConversationTurnUpdateOne) SetNillableCreatedAt(v *time.Time) *ConversationTurnUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the ConversationTurnMutation object of the builder.
func (_u *ConversationTurnUpdateOne) Mutation() *ConversationTurnMutation {
	return _u.mutation
}

// Where appends a list predicates to the ConversationTurnUpdate builder.
func (_u *ConversationTurnUpdateOne) Where(ps ...predicate.ConversationTurn) *ConversationTurnUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConversationTurnUpdateOne) Select(field string, fields ...string) *ConversationTurnUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ConversationTurn entity.
func (_u *ConversationTurnUpdateOne) Save(ctx context.Context) (*ConversationTurn, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationTurnUpdateOne) SaveX(ctx context.Context) *ConversationTurn {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConversationTurnUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationTurnUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationTurnUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := conversationturn.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := conversationturn.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamRequestID(); ok {
		if err := conversationturn.UpstreamRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_request_id", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.upstream_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientRequestID(); ok {
		if err := conversationturn.ClientRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "client_request_id", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.client_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := conversationturn.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := conversationturn.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestPath(); ok {
		if err := conversationturn.RequestPathValidator(v); err != nil {
			return &ValidationError{Name: "request_path", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.request_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QualityStatus(); ok {
		if err := conversationturn.QualityStatusValidator(v); err != nil {
			return &ValidationError{Name: "quality_status", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.quality_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ParseStatus(); ok {
		if err := conversationturn.ParseStatusValidator(v); err != nil {
			return &ValidationError{Name: "parse_status", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.parse_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ParseError(); ok {
		if err := conversationturn.ParseErrorValidator(v); err != nil {
			return &ValidationError{Name: "parse_error", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.parse_error": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DedupeHash(); ok {
		if err := conversationturn.DedupeHashValidator(v); err != nil {
			return &ValidationError{Name: "dedupe_hash", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.dedupe_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RawArchiveKey(); ok {
		if err := conversationturn.RawArchiveKeyValidator(v); err != nil {
			return &ValidationError{Name: "raw_archive_key", err: fmt.Errorf(`ent: validator failed for field "ConversationTurn.raw_archive_key": %w`, err)}
		}
	}
	return nil
}

func (_u *ConversationTurnUpdateOne) sqlSave(ctx context.Context) (_node *ConversationTurn, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversationturn.Table, conversationturn.Columns, sqlgraph.NewFieldSpec(conversationturn.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConversationTurn.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, conversationturn.FieldID)
		for _, f := range fields {
			if !conversationturn.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != conversationturn.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(conversationturn.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(conversationturn.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamRequestID(); ok {
		_spec.SetField(conversationturn.FieldUpstreamRequestID, field.TypeString, value)
	}
	if _u.mutation.UpstreamRequestIDCleared() {
		_spec.ClearField(conversationturn.FieldUpstreamRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.ClientRequestID(); ok {
		_spec.SetField(conversationturn.FieldClientRequestID, field.TypeString, value)
	}
	if _u.mutation.ClientRequestIDCleared() {
		_spec.ClearField(conversationturn.FieldClientRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.TurnIndex(); ok {
		_spec.SetField(conversationturn.FieldTurnIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTurnIndex(); ok {
		_spec.AddField(conversationturn.FieldTurnIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(conversationturn.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(conversationturn.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestPath(); ok {
		_spec.SetField(conversationturn.FieldRequestPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestMessages(); ok {
		_spec.SetField(conversationturn.FieldRequestMessages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequestMessages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, conversationturn.FieldRequestMessages, value)
		})
	}
	if _u.mutation.RequestMessagesCleared() {
		_spec.ClearField(conversationturn.FieldRequestMessages, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResponseMessages(); ok {
		_spec.SetField(conversationturn.FieldResponseMessages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResponseMessages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, conversationturn.FieldResponseMessages, value)
		})
	}
	if _u.mutation.ResponseMessagesCleared() {
		_spec.ClearField(conversationturn.FieldResponseMessages, field.TypeJSON)
	}
	if value, ok := _u.mutation.Tools(); ok {
		_spec.SetField(conversationturn.FieldTools, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTools(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, conversationturn.FieldTools, value)
		})
	}
	if _u.mutation.ToolsCleared() {
		_spec.ClearField(conversationturn.FieldTools, field.TypeJSON)
	}
	if value, ok := _u.mutation.Usage(); ok {
		_spec.SetField(conversationturn.FieldUsage, field.TypeJSON, value)
	}
	if _u.mutation.UsageCleared() {
		_spec.ClearField(conversationturn.FieldUsage, field.TypeJSON)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(conversationturn.FieldMeta, field.TypeJSON, value)
	}
	if _u.mutation.MetaCleared() {
		_spec.ClearField(conversationturn.FieldMeta, field.TypeJSON)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(conversationturn.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(conversationturn.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(conversationturn.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(conversationturn.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(conversationturn.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(conversationturn.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(conversationturn.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(conversationturn.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(conversationturn.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ClientDisconnect(); ok {
		_spec.SetField(conversationturn.FieldClientDisconnect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Truncated(); ok {
		_spec.SetField(conversationturn.FieldTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QualityStatus(); ok {
		_spec.SetField(conversationturn.FieldQualityStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.QualityErrors(); ok {
		_spec.SetField(conversationturn.FieldQualityErrors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedQualityErrors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, conversationturn.FieldQualityErrors, value)
		})
	}
	if _u.mutation.QualityErrorsCleared() {
		_spec.ClearField(conversationturn.FieldQualityErrors, field.TypeJSON)
	}
	if value, ok := _u.mutation.Exportable(); ok {
		_spec.SetField(conversationturn.FieldExportable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ParseStatus(); ok {
		_spec.SetField(conversationturn.FieldParseStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParseError(); ok {
		_spec.SetField(conversationturn.FieldParseError, field.TypeString, value)
	}
	if _u.mutation.ParseErrorCleared() {
		_spec.ClearField(conversationturn.FieldParseError, field.TypeString)
	}
	if value, ok := _u.mutation.DedupeHash(); ok {
		_spec.SetField(conversationturn.FieldDedupeHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.RawArchiveKey(); ok {
		_spec.SetField(conversationturn.FieldRawArchiveKey, field.TypeString, value)
	}
	if _u.mutation.RawArchiveKeyCleared() {
		_spec.ClearField(conversationturn.FieldRawArchiveKey, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadPreview(); ok {
		_spec.SetField(conversationturn.FieldPayloadPreview, field.TypeString, value)
	}
	if _u.mutation.PayloadPreviewCleared() {
		_spec.ClearField(conversationturn.FieldPayloadPreview, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadCompressed(); ok {
		_spec.SetField(conversationturn.FieldPayloadCompressed, field.TypeBytes, value)
	}
	if _u.mutation.PayloadCompressedCleared() {
		_spec.ClearField(conversationturn.FieldPayloadCompressed, field.TypeBytes)
	}
	if value, ok := _u.mutation.RetentionUntil(); ok {
		_spec.SetField(conversationturn.FieldRetentionUntil, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(conversationturn.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &ConversationTurn{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversationturn.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
