// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversationturn"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ConversationTurnDelete is the builder for deleting a ConversationTurn entity.
type ConversationTurnDelete struct {
	config
	hooks    []Hook
	mutation *ConversationTurnMutation
}

// Where appends a list predicates to the ConversationTurnDelete builder.
func (_d *ConversationTurnDelete) Where(ps ...predicate.ConversationTurn) *ConversationTurnDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ConversationTurnDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ConversationTurnDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ConversationTurnDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(conversationturn.Table, sqlgraph.NewFieldSpec(conversationturn.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ConversationTurnDeleteOne is the builder for deleting a single ConversationTurn entity.
type ConversationTurnDeleteOne struct {
	_d *ConversationTurnDelete
}

// Where appends a list predicates to the ConversationTurnDelete builder.
func (_d *ConversationTurnDeleteOne) Where(ps ...predicate.ConversationTurn) *ConversationTurnDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ConversationTurnDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{conversationturn.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ConversationTurnDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
