// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversationexportjob"
)

// ConversationExportJobCreate is the builder for creating a ConversationExportJob entity.
type ConversationExportJobCreate struct {
	config
	mutation *ConversationExportJobMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetStatus sets the "status" field.
func (_c *ConversationExportJobCreate) SetStatus(v string) *ConversationExportJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ConversationExportJobCreate) SetNillableStatus(v *string) *ConversationExportJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetFilters sets the "filters" field.
func (_c *ConversationExportJobCreate) SetFilters(v map[string]jsontext.Value) *ConversationExportJobCreate {
	_c.mutation.SetFilters(v)
	return _c
}

// SetFormat sets the "format" field.
func (_c *ConversationExportJobCreate) SetFormat(v string) *ConversationExportJobCreate {
	_c.mutation.SetFormat(v)
	return _c
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_c *ConversationExportJobCreate) SetNillableFormat(v *string) *ConversationExportJobCreate {
	if v != nil {
		_c.SetFormat(*v)
	}
	return _c
}

// SetEncoding sets the "encoding" field.
func (_c *ConversationExportJobCreate) SetEncoding(v string) *ConversationExportJobCreate {
	_c.mutation.SetEncoding(v)
	return _c
}

// SetNillableEncoding sets the "encoding" field if the given value is not nil.
func (_c *ConversationExportJobCreate) SetNillableEncoding(v *string) *ConversationExportJobCreate {
	if v != nil {
		_c.SetEncoding(*v)
	}
	return _c
}

// SetSessionCount sets the "session_count" field.
func (_c *ConversationExportJobCreate) SetSessionCount(v int64) *ConversationExportJobCreate {
	_c.mutation.SetSessionCount(v)
	return _c
}

// SetNillableSessionCount sets the "session_count" field if the given value is not nil.
func (_c *ConversationExportJobCreate) SetNillableSessionCount(v *int64) *ConversationExportJobCreate {
	if v != nil {
		_c.SetSessionCount(*v)
	}
	return _c
}

// SetTurnCount sets the "turn_count" field.
func (_c *ConversationExportJobCreate) SetTurnCount(v int64) *ConversationExportJobCreate {
	_c.mutation.SetTurnCount(v)
	return _c
}

// SetNillableTurnCount sets the "turn_count" field if the given value is not nil.
func (_c *ConversationExportJobCreate) SetNillableTurnCount(v *int64) *ConversationExportJobCreate {
	if v != nil {
		_c.SetTurnCount(*v)
	}
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *ConversationExportJobCreate) SetFileSize(v int64) *ConversationExportJobCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_c *ConversationExportJobCreate) SetNillableFileSize(v *int64) *ConversationExportJobCreate {
	if v != nil {
		_c.SetFileSize(*v)
	}
	return _c
}

// SetS3Key sets the "s3_key" field.
func (_c *ConversationExportJobCreate) SetS3Key(v string) *ConversationExportJobCreate {
	_c.mutation.SetS3Key(v)
	return _c
}

// SetNillableS3Key sets the "s3_key" field if the given value is not nil.
func (_c *ConversationExportJobCreate) SetNillableS3Key(v *string) *ConversationExportJobCreate {
	if v != nil {
		_c.SetS3Key(*v)
	}
	return _c
}

// SetDownloadURLExpiresAt sets the "download_url_expires_at" field.
func (_c *ConversationExportJobCreate) SetDownloadURLExpiresAt(v time.Time) *ConversationExportJobCreate {
	_c.mutation.SetDownloadURLExpiresAt(v)
	return _c
}

// SetNillableDownloadURLExpiresAt sets the "download_url_expires_at" field if the given value is not nil.
func (_c *ConversationExportJobCreate) SetNillableDownloadURLExpiresAt(v *time.Time) *ConversationExportJobCreate {
	if v != nil {
		_c.SetDownloadURLExpiresAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ConversationExportJobCreate) SetExpiresAt(v time.Time) *ConversationExportJobCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *ConversationExportJobCreate) SetErrorMessage(v string) *ConversationExportJobCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *ConversationExportJobCreate) SetNillableErrorMessage(v *string) *ConversationExportJobCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ConversationExportJobCreate) SetCreatedBy(v int64) *ConversationExportJobCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConversationExportJobCreate) SetCreatedAt(v time.Time) *ConversationExportJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConversationExportJobCreate) SetNillableCreatedAt(v *time.Time) *ConversationExportJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ConversationExportJobCreate) SetUpdatedAt(v time.Time) *ConversationExportJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ConversationExportJobCreate) SetNillableUpdatedAt(v *time.Time) *ConversationExportJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *ConversationExportJobCreate) SetStartedAt(v time.Time) *ConversationExportJobCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *ConversationExportJobCreate) SetNillableStartedAt(v *time.Time) *ConversationExportJobCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *ConversationExportJobCreate) SetCompletedAt(v time.Time) *ConversationExportJobCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *ConversationExportJobCreate) SetNillableCompletedAt(v *time.Time) *ConversationExportJobCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// Mutation returns the ConversationExportJobMutation object of the builder.
func (_c *ConversationExportJobCreate) Mutation() *ConversationExportJobMutation {
	return _c.mutation
}

// Save creates the ConversationExportJob in the database.
func (_c *ConversationExportJobCreate) Save(ctx context.Context) (*ConversationExportJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConversationExportJobCreate) SaveX(ctx context.Context) *ConversationExportJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationExportJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationExportJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConversationExportJobCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := conversationexportjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Format(); !ok {
		v := conversationexportjob.DefaultFormat
		_c.mutation.SetFormat(v)
	}
	if _, ok := _c.mutation.Encoding(); !ok {
		v := conversationexportjob.DefaultEncoding
		_c.mutation.SetEncoding(v)
	}
	if _, ok := _c.mutation.SessionCount(); !ok {
		v := conversationexportjob.DefaultSessionCount
		_c.mutation.SetSessionCount(v)
	}
	if _, ok := _c.mutation.TurnCount(); !ok {
		v := conversationexportjob.DefaultTurnCount
		_c.mutation.SetTurnCount(v)
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		v := conversationexportjob.DefaultFileSize
		_c.mutation.SetFileSize(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := conversationexportjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := conversationexportjob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConversationExportJobCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ConversationExportJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := conversationexportjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ConversationExportJob.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Format(); !ok {
		return &ValidationError{Name: "format", err: errors.New(`ent: missing required field "ConversationExportJob.format"`)}
	}
	if v, ok := _c.mutation.Format(); ok {
		if err := conversationexportjob.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf(`ent: validator failed for field "ConversationExportJob.format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Encoding(); !ok {
		return &ValidationError{Name: "encoding", err: errors.New(`ent: missing required field "ConversationExportJob.encoding"`)}
	}
	if v, ok := _c.mutation.Encoding(); ok {
		if err := conversationexportjob.EncodingValidator(v); err != nil {
			return &ValidationError{Name: "encoding", err: fmt.Errorf(`ent: validator failed for field "ConversationExportJob.encoding": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SessionCount(); !ok {
		return &ValidationError{Name: "session_count", err: errors.New(`ent: missing required field "ConversationExportJob.session_count"`)}
	}
	if _, ok := _c.mutation.TurnCount(); !ok {
		return &ValidationError{Name: "turn_count", err: errors.New(`ent: missing required field "ConversationExportJob.turn_count"`)}
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		return &ValidationError{Name: "file_size", err: errors.New(`ent: missing required field "ConversationExportJob.file_size"`)}
	}
	if v, ok := _c.mutation.S3Key(); ok {
		if err := conversationexportjob.S3KeyValidator(v); err != nil {
			return &ValidationError{Name: "s3_key", err: fmt.Errorf(`ent: validator failed for field "ConversationExportJob.s3_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "ConversationExportJob.expires_at"`)}
	}
	if v, ok := _c.mutation.ErrorMessage(); ok {
		if err := conversationexportjob.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "ConversationExportJob.error_message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "ConversationExportJob.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ConversationExportJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ConversationExportJob.updated_at"`)}
	}
	return nil
}

func (_c *ConversationExportJobCreate) sqlSave(ctx context.Context) (*ConversationExportJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConversationExportJobCreate) createSpec() (*ConversationExportJob, *sqlgraph.CreateSpec) {
	var (
		_node = &ConversationExportJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(conversationexportjob.Table, sqlgraph.NewFieldSpec(conversationexportjob.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(conversationexportjob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Filters(); ok {
		_spec.SetField(conversationexportjob.FieldFilters, field.TypeJSON, value)
		_node.Filters = value
	}
	if value, ok := _c.mutation.Format(); ok {
		_spec.SetField(conversationexportjob.FieldFormat, field.TypeString, value)
		_node.Format = value
	}
	if value, ok := _c.mutation.Encoding(); ok {
		_spec.SetField(conversationexportjob.FieldEncoding, field.TypeString, value)
		_node.Encoding = value
	}
	if value, ok := _c.mutation.SessionCount(); ok {
		_spec.SetField(conversationexportjob.FieldSessionCount, field.TypeInt64, value)
		_node.SessionCount = value
	}
	if value, ok := _c.mutation.TurnCount(); ok {
		_spec.SetField(conversationexportjob.FieldTurnCount, field.TypeInt64, value)
		_node.TurnCount = value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(conversationexportjob.FieldFileSize, field.TypeInt64, value)
		_node.FileSize = value
	}
	if value, ok := _c.mutation.S3Key(); ok {
		_spec.SetField(conversationexportjob.FieldS3Key, field.TypeString, value)
		_node.S3Key = &value
	}
	if value, ok := _c.mutation.DownloadURLExpiresAt(); ok {
		_spec.SetField(conversationexportjob.FieldDownloadURLExpiresAt, field.TypeTime, value)
		_node.DownloadURLExpiresAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(conversationexportjob.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(conversationexportjob.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(conversationexportjob.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(conversationexportjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(conversationexportjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(conversationexportjob.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(conversationexportjob.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ConversationExportJob.Create().
//		SetStatus(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConversationExportJobUpsert) {
//			SetStatus(v+v).
//		}).
//		Exec(ctx)
func (_c *ConversationExportJobCreate) OnConflict(opts ...sql.ConflictOption) *ConversationExportJobUpsertOne {
	_c.conflict = opts
	return &ConversationExportJobUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ConversationExportJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConversationExportJobCreate) OnConflictColumns(columns ...string) *ConversationExportJobUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConversationExportJobUpsertOne{
		create: _c,
	}
}

type (
	// ConversationExportJobUpsertOne is the builder for "upsert"-ing
	//  one ConversationExportJob node.
	ConversationExportJobUpsertOne struct {
		create *ConversationExportJobCreate
	}

	// ConversationExportJobUpsert is the "OnConflict" setter.
	ConversationExportJobUpsert struct {
		*sql.UpdateSet
	}
)

// SetStatus sets the "status" field.
func (u *ConversationExportJobUpsert) SetStatus(v string) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateStatus() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldStatus)
	return u
}

// SetFilters sets the "filters" field.
func (u *ConversationExportJobUpsert) SetFilters(v map[string]jsontext.Value) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldFilters, v)
	return u
}

// UpdateFilters sets the "filters" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateFilters() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldFilters)
	return u
}

// ClearFilters clears the value of the "filters" field.
func (u *ConversationExportJobUpsert) ClearFilters() *ConversationExportJobUpsert {
	u.SetNull(conversationexportjob.FieldFilters)
	return u
}

// SetFormat sets the "format" field.
func (u *ConversationExportJobUpsert) SetFormat(v string) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldFormat, v)
	return u
}

// UpdateFormat sets the "format" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateFormat() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldFormat)
	return u
}

// SetEncoding sets the "encoding" field.
func (u *ConversationExportJobUpsert) SetEncoding(v string) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldEncoding, v)
	return u
}

// UpdateEncoding sets the "encoding" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateEncoding() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldEncoding)
	return u
}

// SetSessionCount sets the "session_count" field.
func (u *ConversationExportJobUpsert) SetSessionCount(v int64) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldSessionCount, v)
	return u
}

// UpdateSessionCount sets the "session_count" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateSessionCount() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldSessionCount)
	return u
}

// AddSessionCount adds v to the "session_count" field.
func (u *ConversationExportJobUpsert) AddSessionCount(v int64) *ConversationExportJobUpsert {
	u.Add(conversationexportjob.FieldSessionCount, v)
	return u
}

// SetTurnCount sets the "turn_count" field.
func (u *ConversationExportJobUpsert) SetTurnCount(v int64) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldTurnCount, v)
	return u
}

// UpdateTurnCount sets the "turn_count" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateTurnCount() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldTurnCount)
	return u
}

// AddTurnCount adds v to the "turn_count" field.
func (u *ConversationExportJobUpsert) AddTurnCount(v int64) *ConversationExportJobUpsert {
	u.Add(conversationexportjob.FieldTurnCount, v)
	return u
}

// SetFileSize sets the "file_size" field.
func (u *ConversationExportJobUpsert) SetFileSize(v int64) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldFileSize, v)
	return u
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateFileSize() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldFileSize)
	return u
}

// AddFileSize adds v to the "file_size" field.
func (u *ConversationExportJobUpsert) AddFileSize(v int64) *ConversationExportJobUpsert {
	u.Add(conversationexportjob.FieldFileSize, v)
	return u
}

// SetS3Key sets the "s3_key" field.
func (u *ConversationExportJobUpsert) SetS3Key(v string) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldS3Key, v)
	return u
}

// UpdateS3Key sets the "s3_key" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateS3Key() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldS3Key)
	return u
}

// ClearS3Key clears the value of the "s3_key" field.
func (u *ConversationExportJobUpsert) ClearS3Key() *ConversationExportJobUpsert {
	u.SetNull(conversationexportjob.FieldS3Key)
	return u
}

// SetDownloadURLExpiresAt sets the "download_url_expires_at" field.
func (u *ConversationExportJobUpsert) SetDownloadURLExpiresAt(v time.Time) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldDownloadURLExpiresAt, v)
	return u
}

// UpdateDownloadURLExpiresAt sets the "download_url_expires_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateDownloadURLExpiresAt() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldDownloadURLExpiresAt)
	return u
}

// ClearDownloadURLExpiresAt clears the value of the "download_url_expires_at" field.
func (u *ConversationExportJobUpsert) ClearDownloadURLExpiresAt() *ConversationExportJobUpsert {
	u.SetNull(conversationexportjob.FieldDownloadURLExpiresAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ConversationExportJobUpsert) SetExpiresAt(v time.Time) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateExpiresAt() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldExpiresAt)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *ConversationExportJobUpsert) SetErrorMessage(v string) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateErrorMessage() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ConversationExportJobUpsert) ClearErrorMessage() *ConversationExportJobUpsert {
	u.SetNull(conversationexportjob.FieldErrorMessage)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ConversationExportJobUpsert) SetCreatedBy(v int64) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateCreatedBy() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ConversationExportJobUpsert) AddCreatedBy(v int64) *ConversationExportJobUpsert {
	u.Add(conversationexportjob.FieldCreatedBy, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ConversationExportJobUpsert) SetCreatedAt(v time.Time) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateCreatedAt() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ConversationExportJobUpsert) SetUpdatedAt(v time.Time) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateUpdatedAt() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldUpdatedAt)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *ConversationExportJobUpsert) SetStartedAt(v time.Time) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateStartedAt() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ConversationExportJobUpsert) ClearStartedAt() *ConversationExportJobUpsert {
	u.SetNull(conversationexportjob.FieldStartedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *ConversationExportJobUpsert) SetCompletedAt(v time.Time) *ConversationExportJobUpsert {
	u.Set(conversationexportjob.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsert) UpdateCompletedAt() *ConversationExportJobUpsert {
	u.SetExcluded(conversationexportjob.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ConversationExportJobUpsert) ClearCompletedAt() *ConversationExportJobUpsert {
	u.SetNull(conversationexportjob.FieldCompletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ConversationExportJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ConversationExportJobUpsertOne) UpdateNewValues() *ConversationExportJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ConversationExportJob.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ConversationExportJobUpsertOne) Ignore() *ConversationExportJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConversationExportJobUpsertOne) DoNothing() *ConversationExportJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConversationExportJobCreate.OnConflict
// documentation for more info.
func (u *ConversationExportJobUpsertOne) Update(set func(*ConversationExportJobUpsert)) *ConversationExportJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConversationExportJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *ConversationExportJobUpsertOne) SetStatus(v string) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateStatus() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateStatus()
	})
}

// SetFilters sets the "filters" field.
func (u *ConversationExportJobUpsertOne) SetFilters(v map[string]jsontext.Value) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetFilters(v)
	})
}

// UpdateFilters sets the "filters" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateFilters() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateFilters()
	})
}

// ClearFilters clears the value of the "filters" field.
func (u *ConversationExportJobUpsertOne) ClearFilters() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.ClearFilters()
	})
}

// SetFormat sets the "format" field.
func (u *ConversationExportJobUpsertOne) SetFormat(v string) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetFormat(v)
	})
}

// UpdateFormat sets the "format" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateFormat() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateFormat()
	})
}

// SetEncoding sets the "encoding" field.
func (u *ConversationExportJobUpsertOne) SetEncoding(v string) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetEncoding(v)
	})
}

// UpdateEncoding sets the "encoding" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateEncoding() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateEncoding()
	})
}

// SetSessionCount sets the "session_count" field.
func (u *ConversationExportJobUpsertOne) SetSessionCount(v int64) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetSessionCount(v)
	})
}

// AddSessionCount adds v to the "session_count" field.
func (u *ConversationExportJobUpsertOne) AddSessionCount(v int64) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.AddSessionCount(v)
	})
}

// UpdateSessionCount sets the "session_count" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateSessionCount() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateSessionCount()
	})
}

// SetTurnCount sets the "turn_count" field.
func (u *ConversationExportJobUpsertOne) SetTurnCount(v int64) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetTurnCount(v)
	})
}

// AddTurnCount adds v to the "turn_count" field.
func (u *ConversationExportJobUpsertOne) AddTurnCount(v int64) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.AddTurnCount(v)
	})
}

// UpdateTurnCount sets the "turn_count" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateTurnCount() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateTurnCount()
	})
}

// SetFileSize sets the "file_size" field.
func (u *ConversationExportJobUpsertOne) SetFileSize(v int64) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *ConversationExportJobUpsertOne) AddFileSize(v int64) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateFileSize() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateFileSize()
	})
}

// SetS3Key sets the "s3_key" field.
func (u *ConversationExportJobUpsertOne) SetS3Key(v string) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetS3Key(v)
	})
}

// UpdateS3Key sets the "s3_key" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateS3Key() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateS3Key()
	})
}

// ClearS3Key clears the value of the "s3_key" field.
func (u *ConversationExportJobUpsertOne) ClearS3Key() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.ClearS3Key()
	})
}

// SetDownloadURLExpiresAt sets the "download_url_expires_at" field.
func (u *ConversationExportJobUpsertOne) SetDownloadURLExpiresAt(v time.Time) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetDownloadURLExpiresAt(v)
	})
}

// UpdateDownloadURLExpiresAt sets the "download_url_expires_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateDownloadURLExpiresAt() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateDownloadURLExpiresAt()
	})
}

// ClearDownloadURLExpiresAt clears the value of the "download_url_expires_at" field.
func (u *ConversationExportJobUpsertOne) ClearDownloadURLExpiresAt() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.ClearDownloadURLExpiresAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ConversationExportJobUpsertOne) SetExpiresAt(v time.Time) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateExpiresAt() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ConversationExportJobUpsertOne) SetErrorMessage(v string) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateErrorMessage() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ConversationExportJobUpsertOne) ClearErrorMessage() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.ClearErrorMessage()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ConversationExportJobUpsertOne) SetCreatedBy(v int64) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ConversationExportJobUpsertOne) AddCreatedBy(v int64) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateCreatedBy() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ConversationExportJobUpsertOne) SetCreatedAt(v time.Time) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateCreatedAt() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ConversationExportJobUpsertOne) SetUpdatedAt(v time.Time) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateUpdatedAt() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *ConversationExportJobUpsertOne) SetStartedAt(v time.Time) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateStartedAt() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ConversationExportJobUpsertOne) ClearStartedAt() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *ConversationExportJobUpsertOne) SetCompletedAt(v time.Time) *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsertOne) UpdateCompletedAt() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ConversationExportJobUpsertOne) ClearCompletedAt() *ConversationExportJobUpsertOne {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *ConversationExportJobUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConversationExportJobCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConversationExportJobUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ConversationExportJobUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ConversationExportJobUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ConversationExportJobCreateBulk is the builder for creating many ConversationExportJob entities in bulk.
type ConversationExportJobCreateBulk struct {
	config
	err      error
	builders []*ConversationExportJobCreate
	conflict []sql.ConflictOption
}

// Save creates the ConversationExportJob entities in the database.
func (_c *ConversationExportJobCreateBulk) Save(ctx context.Context) ([]*ConversationExportJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ConversationExportJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConversationExportJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConversationExportJobCreateBulk) SaveX(ctx context.Context) []*ConversationExportJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationExportJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationExportJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ConversationExportJob.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConversationExportJobUpsert) {
//			SetStatus(v+v).
//		}).
//		Exec(ctx)
func (_c *ConversationExportJobCreateBulk) OnConflict(opts ...sql.ConflictOption) *ConversationExportJobUpsertBulk {
	_c.conflict = opts
	return &ConversationExportJobUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ConversationExportJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConversationExportJobCreateBulk) OnConflictColumns(columns ...string) *ConversationExportJobUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConversationExportJobUpsertBulk{
		create: _c,
	}
}

// ConversationExportJobUpsertBulk is the builder for "upsert"-ing
// a bulk of ConversationExportJob nodes.
type ConversationExportJobUpsertBulk struct {
	create *ConversationExportJobCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ConversationExportJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ConversationExportJobUpsertBulk) UpdateNewValues() *ConversationExportJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ConversationExportJob.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ConversationExportJobUpsertBulk) Ignore() *ConversationExportJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConversationExportJobUpsertBulk) DoNothing() *ConversationExportJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConversationExportJobCreateBulk.OnConflict
// documentation for more info.
func (u *ConversationExportJobUpsertBulk) Update(set func(*ConversationExportJobUpsert)) *ConversationExportJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConversationExportJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *ConversationExportJobUpsertBulk) SetStatus(v string) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateStatus() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateStatus()
	})
}

// SetFilters sets the "filters" field.
func (u *ConversationExportJobUpsertBulk) SetFilters(v map[string]jsontext.Value) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetFilters(v)
	})
}

// UpdateFilters sets the "filters" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateFilters() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateFilters()
	})
}

// ClearFilters clears the value of the "filters" field.
func (u *ConversationExportJobUpsertBulk) ClearFilters() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.ClearFilters()
	})
}

// SetFormat sets the "format" field.
func (u *ConversationExportJobUpsertBulk) SetFormat(v string) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetFormat(v)
	})
}

// UpdateFormat sets the "format" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateFormat() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateFormat()
	})
}

// SetEncoding sets the "encoding" field.
func (u *ConversationExportJobUpsertBulk) SetEncoding(v string) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetEncoding(v)
	})
}

// UpdateEncoding sets the "encoding" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateEncoding() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateEncoding()
	})
}

// SetSessionCount sets the "session_count" field.
func (u *ConversationExportJobUpsertBulk) SetSessionCount(v int64) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetSessionCount(v)
	})
}

// AddSessionCount adds v to the "session_count" field.
func (u *ConversationExportJobUpsertBulk) AddSessionCount(v int64) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.AddSessionCount(v)
	})
}

// UpdateSessionCount sets the "session_count" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateSessionCount() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateSessionCount()
	})
}

// SetTurnCount sets the "turn_count" field.
func (u *ConversationExportJobUpsertBulk) SetTurnCount(v int64) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetTurnCount(v)
	})
}

// AddTurnCount adds v to the "turn_count" field.
func (u *ConversationExportJobUpsertBulk) AddTurnCount(v int64) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.AddTurnCount(v)
	})
}

// UpdateTurnCount sets the "turn_count" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateTurnCount() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateTurnCount()
	})
}

// SetFileSize sets the "file_size" field.
func (u *ConversationExportJobUpsertBulk) SetFileSize(v int64) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *ConversationExportJobUpsertBulk) AddFileSize(v int64) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateFileSize() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateFileSize()
	})
}

// SetS3Key sets the "s3_key" field.
func (u *ConversationExportJobUpsertBulk) SetS3Key(v string) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetS3Key(v)
	})
}

// UpdateS3Key sets the "s3_key" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateS3Key() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateS3Key()
	})
}

// ClearS3Key clears the value of the "s3_key" field.
func (u *ConversationExportJobUpsertBulk) ClearS3Key() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.ClearS3Key()
	})
}

// SetDownloadURLExpiresAt sets the "download_url_expires_at" field.
func (u *ConversationExportJobUpsertBulk) SetDownloadURLExpiresAt(v time.Time) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetDownloadURLExpiresAt(v)
	})
}

// UpdateDownloadURLExpiresAt sets the "download_url_expires_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateDownloadURLExpiresAt() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateDownloadURLExpiresAt()
	})
}

// ClearDownloadURLExpiresAt clears the value of the "download_url_expires_at" field.
func (u *ConversationExportJobUpsertBulk) ClearDownloadURLExpiresAt() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.ClearDownloadURLExpiresAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ConversationExportJobUpsertBulk) SetExpiresAt(v time.Time) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateExpiresAt() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ConversationExportJobUpsertBulk) SetErrorMessage(v string) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateErrorMessage() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ConversationExportJobUpsertBulk) ClearErrorMessage() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.ClearErrorMessage()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ConversationExportJobUpsertBulk) SetCreatedBy(v int64) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ConversationExportJobUpsertBulk) AddCreatedBy(v int64) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateCreatedBy() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ConversationExportJobUpsertBulk) SetCreatedAt(v time.Time) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateCreatedAt() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ConversationExportJobUpsertBulk) SetUpdatedAt(v time.Time) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateUpdatedAt() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *ConversationExportJobUpsertBulk) SetStartedAt(v time.Time) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateStartedAt() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ConversationExportJobUpsertBulk) ClearStartedAt() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *ConversationExportJobUpsertBulk) SetCompletedAt(v time.Time) *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ConversationExportJobUpsertBulk) UpdateCompletedAt() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ConversationExportJobUpsertBulk) ClearCompletedAt() *ConversationExportJobUpsertBulk {
	return u.Update(func(s *ConversationExportJobUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *ConversationExportJobUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ConversationExportJobCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConversationExportJobCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConversationExportJobUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
