// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"encoding/json/jsontext"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/conversationsession"
)

// ConversationSession is the model entity for the ConversationSession schema.
type ConversationSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// TrajectoryID holds the value of the "trajectory_id" field.
	TrajectoryID *string `json:"trajectory_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int64 `json:"account_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// RequestPath holds the value of the "request_path" field.
	RequestPath string `json:"request_path,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// TurnCount holds the value of the "turn_count" field.
	TurnCount int `json:"turn_count,omitempty"`
	// SourceRequestCount holds the value of the "source_request_count" field.
	SourceRequestCount int `json:"source_request_count,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int64 `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int64 `json:"output_tokens,omitempty"`
	// TotalTokens holds the value of the "total_tokens" field.
	TotalTokens int64 `json:"total_tokens,omitempty"`
	// ActualCost holds the value of the "actual_cost" field.
	ActualCost float64 `json:"actual_cost,omitempty"`
	// QualityStatus holds the value of the "quality_status" field.
	QualityStatus string `json:"quality_status,omitempty"`
	// QualityErrors holds the value of the "quality_errors" field.
	QualityErrors []jsontext.Value `json:"quality_errors,omitempty"`
	// Exportable holds the value of the "exportable" field.
	Exportable bool `json:"exportable,omitempty"`
	// CaptureStatus holds the value of the "capture_status" field.
	CaptureStatus string `json:"capture_status,omitempty"`
	// SessionSource holds the value of the "session_source" field.
	SessionSource string `json:"session_source,omitempty"`
	// RetentionUntil holds the value of the "retention_until" field.
	RetentionUntil time.Time `json:"retention_until,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// EndedAt holds the value of the "ended_at" field.
	EndedAt time.Time `json:"ended_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ConversationSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case conversationsession.FieldQualityErrors:
			values[i] = new([]byte)
		case conversationsession.FieldExportable:
			values[i] = new(sql.NullBool)
		case conversationsession.FieldActualCost:
			values[i] = new(sql.NullFloat64)
		case conversationsession.FieldID, conversationsession.FieldUserID, conversationsession.FieldAPIKeyID, conversationsession.FieldAccountID, conversationsession.FieldTurnCount, conversationsession.FieldSourceRequestCount, conversationsession.FieldInputTokens, conversationsession.FieldOutputTokens, conversationsession.FieldTotalTokens:
			values[i] = new(sql.NullInt64)
		case conversationsession.FieldSessionID, conversationsession.FieldTrajectoryID, conversationsession.FieldProvider, conversationsession.FieldModel, conversationsession.FieldRequestPath, conversationsession.FieldStatus, conversationsession.FieldQualityStatus, conversationsession.FieldCaptureStatus, conversationsession.FieldSessionSource:
			values[i] = new(sql.NullString)
		case conversationsession.FieldRetentionUntil, conversationsession.FieldStartedAt, conversationsession.FieldEndedAt, conversationsession.FieldCreatedAt, conversationsession.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ConversationSession fields.
func (_m *ConversationSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case conversationsession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case conversationsession.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case conversationsession.FieldTrajectoryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trajectory_id", values[i])
			} else if value.Valid {
				_m.TrajectoryID = new(string)
				*_m.TrajectoryID = value.String
			}
		case conversationsession.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case conversationsession.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case conversationsession.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case conversationsession.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case conversationsession.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case conversationsession.FieldRequestPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_path", values[i])
			} else if value.Valid {
				_m.RequestPath = value.String
			}
		case conversationsession.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case conversationsession.FieldTurnCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field turn_count", values[i])
			} else if value.Valid {
				_m.TurnCount = int(value.Int64)
			}
		case conversationsession.FieldSourceRequestCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_request_count", values[i])
			} else if value.Valid {
				_m.SourceRequestCount = int(value.Int64)
			}
		case conversationsession.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = value.Int64
			}
		case conversationsession.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = value.Int64
			}
		case conversationsession.FieldTotalTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_tokens", values[i])
			} else if value.Valid {
				_m.TotalTokens = value.Int64
			}
		case conversationsession.FieldActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost", values[i])
			} else if value.Valid {
				_m.ActualCost = value.Float64
			}
		case conversationsession.FieldQualityStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quality_status", values[i])
			} else if value.Valid {
				_m.QualityStatus = value.String
			}
		case conversationsession.FieldQualityErrors:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field quality_errors", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.QualityErrors); err != nil {
					return fmt.Errorf("unmarshal field quality_errors: %w", err)
				}
			}
		case conversationsession.FieldExportable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field exportable", values[i])
			} else if value.Valid {
				_m.Exportable = value.Bool
			}
		case conversationsession.FieldCaptureStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field capture_status", values[i])
			} else if value.Valid {
				_m.CaptureStatus = value.String
			}
		case conversationsession.FieldSessionSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_source", values[i])
			} else if value.Valid {
				_m.SessionSource = value.String
			}
		case conversationsession.FieldRetentionUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field retention_until", values[i])
			} else if value.Valid {
				_m.RetentionUntil = value.Time
			}
		case conversationsession.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case conversationsession.FieldEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				_m.EndedAt = value.Time
			}
		case conversationsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case conversationsession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ConversationSession.
// This includes values selected through modifiers, order, etc.
func (_m *ConversationSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ConversationSession.
// Note that you need to call ConversationSession.Unwrap() before calling this method if this ConversationSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ConversationSession) Update() *ConversationSessionUpdateOne {
	return NewConversationSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ConversationSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ConversationSession) Unwrap() *ConversationSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ConversationSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ConversationSession) String() string {
	var builder strings.Builder
	builder.WriteString("ConversationSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	if v := _m.TrajectoryID; v != nil {
		builder.WriteString("trajectory_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("request_path=")
	builder.WriteString(_m.RequestPath)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("turn_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TurnCount))
	builder.WriteString(", ")
	builder.WriteString("source_request_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceRequestCount))
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("total_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalTokens))
	builder.WriteString(", ")
	builder.WriteString("actual_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActualCost))
	builder.WriteString(", ")
	builder.WriteString("quality_status=")
	builder.WriteString(_m.QualityStatus)
	builder.WriteString(", ")
	builder.WriteString("quality_errors=")
	builder.WriteString(fmt.Sprintf("%v", _m.QualityErrors))
	builder.WriteString(", ")
	builder.WriteString("exportable=")
	builder.WriteString(fmt.Sprintf("%v", _m.Exportable))
	builder.WriteString(", ")
	builder.WriteString("capture_status=")
	builder.WriteString(_m.CaptureStatus)
	builder.WriteString(", ")
	builder.WriteString("session_source=")
	builder.WriteString(_m.SessionSource)
	builder.WriteString(", ")
	builder.WriteString("retention_until=")
	builder.WriteString(_m.RetentionUntil.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ended_at=")
	builder.WriteString(_m.EndedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ConversationSessions is a parsable slice of ConversationSession.
type ConversationSessions []*ConversationSession
