// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversationexportjob"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ConversationExportJobUpdate is the builder for updating ConversationExportJob entities.
type ConversationExportJobUpdate struct {
	config
	hooks    []Hook
	mutation *ConversationExportJobMutation
}

// Where appends a list predicates to the ConversationExportJobUpdate builder.
func (_u *ConversationExportJobUpdate) Where(ps ...predicate.ConversationExportJob) *ConversationExportJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ConversationExportJobUpdate) SetStatus(v string) *ConversationExportJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ConversationExportJobUpdate) SetNillableStatus(v *string) *ConversationExportJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFilters sets the "filters" field.
func (_u *ConversationExportJobUpdate) SetFilters(v map[string]jsontext.Value) *ConversationExportJobUpdate {
	_u.mutation.SetFilters(v)
	return _u
}

// ClearFilters clears the value of the "filters" field.
func (_u *ConversationExportJobUpdate) ClearFilters() *ConversationExportJobUpdate {
	_u.mutation.ClearFilters()
	return _u
}

// SetFormat sets the "format" field.
func (_u *ConversationExportJobUpdate) SetFormat(v string) *ConversationExportJobUpdate {
	_u.mutation.SetFormat(v)
	return _u
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_u *ConversationExportJobUpdate) SetNillableFormat(v *string) *ConversationExportJobUpdate {
	if v != nil {
		_u.SetFormat(*v)
	}
	return _u
}

// SetEncoding sets the "encoding" field.
func (_u *ConversationExportJobUpdate) SetEncoding(v string) *ConversationExportJobUpdate {
	_u.mutation.SetEncoding(v)
	return _u
}

// SetNillableEncoding sets the "encoding" field if the given value is not nil.
func (_u *ConversationExportJobUpdate) SetNillableEncoding(v *string) *ConversationExportJobUpdate {
	if v != nil {
		_u.SetEncoding(*v)
	}
	return _u
}

// SetSessionCount sets the "session_count" field.
func (_u *ConversationExportJobUpdate) SetSessionCount(v int64) *ConversationExportJobUpdate {
	_u.mutation.ResetSessionCount()
	_u.mutation.SetSessionCount(v)
	return _u
}

// SetNillableSessionCount sets the "session_count" field if the given value is not nil.
func (_u *ConversationExportJobUpdate) SetNillableSessionCount(v *int64) *ConversationExportJobUpdate {
	if v != nil {
		_u.SetSessionCount(*v)
	}
	return _u
}

// AddSessionCount adds value to the "session_count" field.
func (_u *ConversationExportJobUpdate) AddSessionCount(v int64) *ConversationExportJobUpdate {
	_u.mutation.AddSessionCount(v)
	return _u
}

// SetTurnCount sets the "turn_count" field.
func (_u *ConversationExportJobUpdate) SetTurnCount(v int64) *ConversationExportJobUpdate {
	_u.mutation.ResetTurnCount()
	_u.mutation.SetTurnCount(v)
	return _u
}

// SetNillableTurnCount sets the "turn_count" field if the given value is not nil.
func (_u *ConversationExportJobUpdate) SetNillableTurnCount(v *int64) *ConversationExportJobUpdate {
	if v != nil {
		_u.SetTurnCount(*v)
	}
	return _u
}

// AddTurnCount adds value to the "turn_count" field.
func (_u *ConversationExportJobUpdate) AddTurnCount(v int64) *ConversationExportJobUpdate {
	_u.mutation.AddTurnCount(v)
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *ConversationExportJobUpdate) SetFileSize(v int64) *ConversationExportJobUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *ConversationExportJobUpdate) SetNillableFileSize(v *int64) *ConversationExportJobUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *ConversationExportJobUpdate) AddFileSize(v int64) *ConversationExportJobUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetS3Key sets the "s3_key" field.
func (_u *ConversationExportJobUpdate) SetS3Key(v string) *ConversationExportJobUpdate {
	_u.mutation.SetS3Key(v)
	return _u
}

// SetNillableS3Key sets the "s3_key" field if the given value is not nil.
func (_u *ConversationExportJobUpdate) SetNillableS3Key(v *string) *ConversationExportJobUpdate {
	if v != nil {
		_u.SetS3Key(*v)
	}
	return _u
}

// ClearS3Key clears the value of the "s3_key" field.
func (_u *ConversationExportJobUpdate) ClearS3Key() *ConversationExportJobUpdate {
	_u.mutation.ClearS3Key()
	return _u
}

// SetDownloadURLExpiresAt sets the "download_url_expires_at" field.
func (_u *ConversationExportJobUpdate) SetDownloadURLExpiresAt(v time.Time) *ConversationExportJobUpdate {
	_u.mutation.SetDownloadURLExpiresAt(v)
	return _u
}

// SetNillableDownloadURLExpiresAt sets the "download_url_expires_at" field if the given value is not nil.
func (_u *ConversationExportJobUpdate) SetNillableDownloadURLExpiresAt(v *time.Time) *ConversationExportJobUpdate {
	if v != nil {
		_u.SetDownloadURLExpiresAt(*v)
	}
	return _u
}

// ClearDownloadURLExpiresAt clears the value of the "download_url_expires_at" field.
func (_u *ConversationExportJobUpdate) ClearDownloadURLExpiresAt() *ConversationExportJobUpdate {
	_u.mutation.ClearDownloadURLExpiresAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ConversationExportJobUpdate) SetExpiresAt(v time.Time) *ConversationExportJobUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ConversationExportJobUpdate) SetNillableExpiresAt(v *time.Time) *ConversationExportJobUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ConversationExportJobUpdate) SetErrorMessage(v string) *ConversationExportJobUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ConversationExportJobUpdate) SetNillableErrorMessage(v *string) *ConversationExportJobUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ConversationExportJobUpdate) ClearErrorMessage() *ConversationExportJobUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ConversationExportJobUpdate) SetCreatedBy(v int64) *ConversationExportJobUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ConversationExportJobUpdate) SetNillableCreatedBy(v *int64) *ConversationExportJobUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ConversationExportJobUpdate) AddCreatedBy(v int64) *ConversationExportJobUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ConversationExportJobUpdate) SetCreatedAt(v time.Time) *ConversationExportJobUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ConversationExportJobUpdate) SetNillableCreatedAt(v *time.Time) *ConversationExportJobUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConversationExportJobUpdate) SetUpdatedAt(v time.Time) *ConversationExportJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ConversationExportJobUpdate) SetStartedAt(v time.Time) *ConversationExportJobUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ConversationExportJobUpdate) SetNillableStartedAt(v *time.Time) *ConversationExportJobUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ConversationExportJobUpdate) ClearStartedAt() *ConversationExportJobUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ConversationExportJobUpdate) SetCompletedAt(v time.Time) *ConversationExportJobUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ConversationExportJobUpdate) SetNillableCompletedAt(v *time.Time) *ConversationExportJobUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ConversationExportJobUpdate) ClearCompletedAt() *ConversationExportJobUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the ConversationExportJobMutation object of the builder.
func (_u *ConversationExportJobUpdate) Mutation() *ConversationExportJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConversationExportJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationExportJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConversationExportJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationExportJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConversationExportJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := conversationexportjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationExportJobUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := conversationexportjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ConversationExportJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Format(); ok {
		if err := conversationexportjob.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf(`ent: validator failed for field "ConversationExportJob.format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Encoding(); ok {
		if err := conversationexportjob.EncodingValidator(v); err != nil {
			return &ValidationError{Name: "encoding", err: fmt.Errorf(`ent: validator failed for field "ConversationExportJob.encoding": %w`, err)}
		}
	}
	if v, ok := _u.mutation.S3Key(); ok {
		if err := conversationexportjob.S3KeyValidator(v); err != nil {
			return &ValidationError{Name: "s3_key", err: fmt.Errorf(`ent: validator failed for field "ConversationExportJob.s3_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := conversationexportjob.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "ConversationExportJob.error_message": %w`, err)}
		}
	}
	return nil
}

func (_u *ConversationExportJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversationexportjob.Table, conversationexportjob.Columns, sqlgraph.NewFieldSpec(conversationexportjob.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(conversationexportjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filters(); ok {
		_spec.SetField(conversationexportjob.FieldFilters, field.TypeJSON, value)
	}
	if _u.mutation.FiltersCleared() {
		_spec.ClearField(conversationexportjob.FieldFilters, field.TypeJSON)
	}
	if value, ok := _u.mutation.Format(); ok {
		_spec.SetField(conversationexportjob.FieldFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Encoding(); ok {
		_spec.SetField(conversationexportjob.FieldEncoding, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionCount(); ok {
		_spec.SetField(conversationexportjob.FieldSessionCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSessionCount(); ok {
		_spec.AddField(conversationexportjob.FieldSessionCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TurnCount(); ok {
		_spec.SetField(conversationexportjob.FieldTurnCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTurnCount(); ok {
		_spec.AddField(conversationexportjob.FieldTurnCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(conversationexportjob.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(conversationexportjob.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.S3Key(); ok {
		_spec.SetField(conversationexportjob.FieldS3Key, field.TypeString, value)
	}
	if _u.mutation.S3KeyCleared() {
		_spec.ClearField(conversationexportjob.FieldS3Key, field.TypeString)
	}
	if value, ok := _u.mutation.DownloadURLExpiresAt(); ok {
		_spec.SetField(conversationexportjob.FieldDownloadURLExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.DownloadURLExpiresAtCleared() {
		_spec.ClearField(conversationexportjob.FieldDownloadURLExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(conversationexportjob.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(conversationexportjob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(conversationexportjob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(conversationexportjob.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(conversationexportjob.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(conversationexportjob.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(conversationexportjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(conversationexportjob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(conversationexportjob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(conversationexportjob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(conversationexportjob.FieldCompletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversationexportjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConversationExportJobUpdateOne is the builder for updating a single ConversationExportJob entity.
type ConversationExportJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConversationExportJobMutation
}

// SetStatus sets the "status" field.
func (_u *ConversationExportJobUpdateOne) SetStatus(v string) *ConversationExportJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ConversationExportJobUpdateOne) SetNillableStatus(v *string) *ConversationExportJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFilters sets the "filters" field.
func (_u *ConversationExportJobUpdateOne) SetFilters(v map[string]jsontext.Value) *ConversationExportJobUpdateOne {
	_u.mutation.SetFilters(v)
	return _u
}

// ClearFilters clears the value of the "filters" field.
func (_u *ConversationExportJobUpdateOne) ClearFilters() *ConversationExportJobUpdateOne {
	_u.mutation.ClearFilters()
	return _u
}

// SetFormat sets the "format" field.
func (_u *ConversationExportJobUpdateOne) SetFormat(v string) *ConversationExportJobUpdateOne {
	_u.mutation.SetFormat(v)
	return _u
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_u *ConversationExportJobUpdateOne) SetNillableFormat(v *string) *ConversationExportJobUpdateOne {
	if v != nil {
		_u.SetFormat(*v)
	}
	return _u
}

// SetEncoding sets the "encoding" field.
func (_u *ConversationExportJobUpdateOne) SetEncoding(v string) *ConversationExportJobUpdateOne {
	_u.mutation.SetEncoding(v)
	return _u
}

// SetNillableEncoding sets the "encoding" field if the given value is not nil.
func (_u *ConversationExportJobUpdateOne) SetNillableEncoding(v *string) *ConversationExportJobUpdateOne {
	if v != nil {
		_u.SetEncoding(*v)
	}
	return _u
}

// SetSessionCount sets the "session_count" field.
func (_u *ConversationExportJobUpdateOne) SetSessionCount(v int64) *ConversationExportJobUpdateOne {
	_u.mutation.ResetSessionCount()
	_u.mutation.SetSessionCount(v)
	return _u
}

// SetNillableSessionCount sets the "session_count" field if the given value is not nil.
func (_u *ConversationExportJobUpdateOne) SetNillableSessionCount(v *int64) *ConversationExportJobUpdateOne {
	if v != nil {
		_u.SetSessionCount(*v)
	}
	return _u
}

// AddSessionCount adds value to the "session_count" field.
func (_u *ConversationExportJobUpdateOne) AddSessionCount(v int64) *ConversationExportJobUpdateOne {
	_u.mutation.AddSessionCount(v)
	return _u
}

// SetTurnCount sets the "turn_count" field.
func (_u *ConversationExportJobUpdateOne) SetTurnCount(v int64) *ConversationExportJobUpdateOne {
	_u.mutation.ResetTurnCount()
	_u.mutation.SetTurnCount(v)
	return _u
}

// SetNillableTurnCount sets the "turn_count" field if the given value is not nil.
func (_u *ConversationExportJobUpdateOne) SetNillableTurnCount(v *int64) *ConversationExportJobUpdateOne {
	if v != nil {
		_u.SetTurnCount(*v)
	}
	return _u
}

// AddTurnCount adds value to the "turn_count" field.
func (_u *ConversationExportJobUpdateOne) AddTurnCount(v int64) *ConversationExportJobUpdateOne {
	_u.mutation.AddTurnCount(v)
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *ConversationExportJobUpdateOne) SetFileSize(v int64) *ConversationExportJobUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *ConversationExportJobUpdateOne) SetNillableFileSize(v *int64) *ConversationExportJobUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *ConversationExportJobUpdateOne) AddFileSize(v int64) *ConversationExportJobUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetS3Key sets the "s3_key" field.
func (_u *ConversationExportJobUpdateOne) SetS3Key(v string) *ConversationExportJobUpdateOne {
	_u.mutation.SetS3Key(v)
	return _u
}

// SetNillableS3Key sets the "s3_key" field if the given value is not nil.
func (_u *ConversationExportJobUpdateOne) SetNillableS3Key(v *string) *ConversationExportJobUpdateOne {
	if v != nil {
		_u.SetS3Key(*v)
	}
	return _u
}

// ClearS3Key clears the value of the "s3_key" field.
func (_u *ConversationExportJobUpdateOne) ClearS3Key() *ConversationExportJobUpdateOne {
	_u.mutation.ClearS3Key()
	return _u
}

// SetDownloadURLExpiresAt sets the "download_url_expires_at" field.
func (_u *ConversationExportJobUpdateOne) SetDownloadURLExpiresAt(v time.Time) *ConversationExportJobUpdateOne {
	_u.mutation.SetDownloadURLExpiresAt(v)
	return _u
}

// SetNillableDownloadURLExpiresAt sets the "download_url_expires_at" field if the given value is not nil.
func (_u *ConversationExportJobUpdateOne) SetNillableDownloadURLExpiresAt(v *time.Time) *ConversationExportJobUpdateOne {
	if v != nil {
		_u.SetDownloadURLExpiresAt(*v)
	}
	return _u
}

// ClearDownloadURLExpiresAt clears the value of the "download_url_expires_at" field.
func (_u *ConversationExportJobUpdateOne) ClearDownloadURLExpiresAt() *ConversationExportJobUpdateOne {
	_u.mutation.ClearDownloadURLExpiresAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ConversationExportJobUpdateOne) SetExpiresAt(v time.Time) *ConversationExportJobUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ConversationExportJobUpdateOne) SetNillableExpiresAt(v *time.Time) *ConversationExportJobUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ConversationExportJobUpdateOne) SetErrorMessage(v string) *ConversationExportJobUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ConversationExportJobUpdateOne) SetNillableErrorMessage(v *string) *ConversationExportJobUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ConversationExportJobUpdateOne) ClearErrorMessage() *ConversationExportJobUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ConversationExportJobUpdateOne) SetCreatedBy(v int64) *ConversationExportJobUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ConversationExportJobUpdateOne) SetNillableCreatedBy(v *int64) *ConversationExportJobUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ConversationExportJobUpdateOne) AddCreatedBy(v int64) *ConversationExportJobUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ConversationExportJobUpdateOne) SetCreatedAt(v time.Time) *ConversationExportJobUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ConversationExportJobUpdateOne) SetNillableCreatedAt(v *time.Time) *ConversationExportJobUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConversationExportJobUpdateOne) SetUpdatedAt(v time.Time) *ConversationExportJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ConversationExportJobUpdateOne) SetStartedAt(v time.Time) *ConversationExportJobUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ConversationExportJobUpdateOne) SetNillableStartedAt(v *time.Time) *ConversationExportJobUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ConversationExportJobUpdateOne) ClearStartedAt() *ConversationExportJobUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ConversationExportJobUpdateOne) SetCompletedAt(v time.Time) *ConversationExportJobUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ConversationExportJobUpdateOne) SetNillableCompletedAt(v *time.Time) *ConversationExportJobUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ConversationExportJobUpdateOne) ClearCompletedAt() *ConversationExportJobUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the ConversationExportJobMutation object of the builder.
func (_u *ConversationExportJobUpdateOne) Mutation() *ConversationExportJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the ConversationExportJobUpdate builder.
func (_u *ConversationExportJobUpdateOne) Where(ps ...predicate.ConversationExportJob) *ConversationExportJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConversationExportJobUpdateOne) Select(field string, fields ...string) *ConversationExportJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ConversationExportJob entity.
func (_u *ConversationExportJobUpdateOne) Save(ctx context.Context) (*ConversationExportJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationExportJobUpdateOne) SaveX(ctx context.Context) *ConversationExportJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConversationExportJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationExportJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConversationExportJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := conversationexportjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationExportJobUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := conversationexportjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ConversationExportJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Format(); ok {
		if err := conversationexportjob.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf(`ent: validator failed for field "ConversationExportJob.format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Encoding(); ok {
		if err := conversationexportjob.EncodingValidator(v); err != nil {
			return &ValidationError{Name: "encoding", err: fmt.Errorf(`ent: validator failed for field "ConversationExportJob.encoding": %w`, err)}
		}
	}
	if v, ok := _u.mutation.S3Key(); ok {
		if err := conversationexportjob.S3KeyValidator(v); err != nil {
			return &ValidationError{Name: "s3_key", err: fmt.Errorf(`ent: validator failed for field "ConversationExportJob.s3_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := conversationexportjob.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "ConversationExportJob.error_message": %w`, err)}
		}
	}
	return nil
}

func (_u *ConversationExportJobUpdateOne) sqlSave(ctx context.Context) (_node *ConversationExportJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversationexportjob.Table, conversationexportjob.Columns, sqlgraph.NewFieldSpec(conversationexportjob.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConversationExportJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, conversationexportjob.FieldID)
		for _, f := range fields {
			if !conversationexportjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != conversationexportjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(conversationexportjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filters(); ok {
		_spec.SetField(conversationexportjob.FieldFilters, field.TypeJSON, value)
	}
	if _u.mutation.FiltersCleared() {
		_spec.ClearField(conversationexportjob.FieldFilters, field.TypeJSON)
	}
	if value, ok := _u.mutation.Format(); ok {
		_spec.SetField(conversationexportjob.FieldFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Encoding(); ok {
		_spec.SetField(conversationexportjob.FieldEncoding, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionCount(); ok {
		_spec.SetField(conversationexportjob.FieldSessionCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSessionCount(); ok {
		_spec.AddField(conversationexportjob.FieldSessionCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TurnCount(); ok {
		_spec.SetField(conversationexportjob.FieldTurnCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTurnCount(); ok {
		_spec.AddField(conversationexportjob.FieldTurnCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(conversationexportjob.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(conversationexportjob.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.S3Key(); ok {
		_spec.SetField(conversationexportjob.FieldS3Key, field.TypeString, value)
	}
	if _u.mutation.S3KeyCleared() {
		_spec.ClearField(conversationexportjob.FieldS3Key, field.TypeString)
	}
	if value, ok := _u.mutation.DownloadURLExpiresAt(); ok {
		_spec.SetField(conversationexportjob.FieldDownloadURLExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.DownloadURLExpiresAtCleared() {
		_spec.ClearField(conversationexportjob.FieldDownloadURLExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(conversationexportjob.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(conversationexportjob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(conversationexportjob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(conversationexportjob.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(conversationexportjob.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(conversationexportjob.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(conversationexportjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(conversationexportjob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(conversationexportjob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(conversationexportjob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(conversationexportjob.FieldCompletedAt, field.TypeTime)
	}
	_node = &ConversationExportJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversationexportjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
