// Code generated by ent, DO NOT EDIT.

package conversationsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldSessionID, v))
}

// TrajectoryID applies equality check predicate on the "trajectory_id" field. It's identical to TrajectoryIDEQ.
func TrajectoryID(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldTrajectoryID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldAPIKeyID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldAccountID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldProvider, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldModel, v))
}

// RequestPath applies equality check predicate on the "request_path" field. It's identical to RequestPathEQ.
func RequestPath(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldRequestPath, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldStatus, v))
}

// TurnCount applies equality check predicate on the "turn_count" field. It's identical to TurnCountEQ.
func TurnCount(v int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldTurnCount, v))
}

// SourceRequestCount applies equality check predicate on the "source_request_count" field. It's identical to SourceRequestCountEQ.
func SourceRequestCount(v int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldSourceRequestCount, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldOutputTokens, v))
}

// TotalTokens applies equality check predicate on the "total_tokens" field. It's identical to TotalTokensEQ.
func TotalTokens(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldTotalTokens, v))
}

// ActualCost applies equality check predicate on the "actual_cost" field. It's identical to ActualCostEQ.
func ActualCost(v float64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldActualCost, v))
}

// QualityStatus applies equality check predicate on the "quality_status" field. It's identical to QualityStatusEQ.
func QualityStatus(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldQualityStatus, v))
}

// Exportable applies equality check predicate on the "exportable" field. It's identical to ExportableEQ.
func Exportable(v bool) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldExportable, v))
}

// CaptureStatus applies equality check predicate on the "capture_status" field. It's identical to CaptureStatusEQ.
func CaptureStatus(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldCaptureStatus, v))
}

// SessionSource applies equality check predicate on the "session_source" field. It's identical to SessionSourceEQ.
func SessionSource(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldSessionSource, v))
}

// RetentionUntil applies equality check predicate on the "retention_until" field. It's identical to RetentionUntilEQ.
func RetentionUntil(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldRetentionUntil, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldStartedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldEndedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContainsFold(FieldSessionID, v))
}

// TrajectoryIDEQ applies the EQ predicate on the "trajectory_id" field.
func TrajectoryIDEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldTrajectoryID, v))
}

// TrajectoryIDNEQ applies the NEQ predicate on the "trajectory_id" field.
func TrajectoryIDNEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldTrajectoryID, v))
}

// TrajectoryIDIn applies the In predicate on the "trajectory_id" field.
func TrajectoryIDIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldTrajectoryID, vs...))
}

// TrajectoryIDNotIn applies the NotIn predicate on the "trajectory_id" field.
func TrajectoryIDNotIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldTrajectoryID, vs...))
}

// TrajectoryIDGT applies the GT predicate on the "trajectory_id" field.
func TrajectoryIDGT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldTrajectoryID, v))
}

// TrajectoryIDGTE applies the GTE predicate on the "trajectory_id" field.
func TrajectoryIDGTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldTrajectoryID, v))
}

// TrajectoryIDLT applies the LT predicate on the "trajectory_id" field.
func TrajectoryIDLT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldTrajectoryID, v))
}

// TrajectoryIDLTE applies the LTE predicate on the "trajectory_id" field.
func TrajectoryIDLTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldTrajectoryID, v))
}

// TrajectoryIDContains applies the Contains predicate on the "trajectory_id" field.
func TrajectoryIDContains(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContains(FieldTrajectoryID, v))
}

// TrajectoryIDHasPrefix applies the HasPrefix predicate on the "trajectory_id" field.
func TrajectoryIDHasPrefix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasPrefix(FieldTrajectoryID, v))
}

// TrajectoryIDHasSuffix applies the HasSuffix predicate on the "trajectory_id" field.
func TrajectoryIDHasSuffix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasSuffix(FieldTrajectoryID, v))
}

// TrajectoryIDIsNil applies the IsNil predicate on the "trajectory_id" field.
func TrajectoryIDIsNil() predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIsNull(FieldTrajectoryID))
}

// TrajectoryIDNotNil applies the NotNil predicate on the "trajectory_id" field.
func TrajectoryIDNotNil() predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotNull(FieldTrajectoryID))
}

// TrajectoryIDEqualFold applies the EqualFold predicate on the "trajectory_id" field.
func TrajectoryIDEqualFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEqualFold(FieldTrajectoryID, v))
}

// TrajectoryIDContainsFold applies the ContainsFold predicate on the "trajectory_id" field.
func TrajectoryIDContainsFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContainsFold(FieldTrajectoryID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldAPIKeyID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotNull(FieldAccountID))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContainsFold(FieldProvider, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContainsFold(FieldModel, v))
}

// RequestPathEQ applies the EQ predicate on the "request_path" field.
func RequestPathEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldRequestPath, v))
}

// RequestPathNEQ applies the NEQ predicate on the "request_path" field.
func RequestPathNEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldRequestPath, v))
}

// RequestPathIn applies the In predicate on the "request_path" field.
func RequestPathIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldRequestPath, vs...))
}

// RequestPathNotIn applies the NotIn predicate on the "request_path" field.
func RequestPathNotIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldRequestPath, vs...))
}

// RequestPathGT applies the GT predicate on the "request_path" field.
func RequestPathGT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldRequestPath, v))
}

// RequestPathGTE applies the GTE predicate on the "request_path" field.
func RequestPathGTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldRequestPath, v))
}

// RequestPathLT applies the LT predicate on the "request_path" field.
func RequestPathLT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldRequestPath, v))
}

// RequestPathLTE applies the LTE predicate on the "request_path" field.
func RequestPathLTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldRequestPath, v))
}

// RequestPathContains applies the Contains predicate on the "request_path" field.
func RequestPathContains(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContains(FieldRequestPath, v))
}

// RequestPathHasPrefix applies the HasPrefix predicate on the "request_path" field.
func RequestPathHasPrefix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasPrefix(FieldRequestPath, v))
}

// RequestPathHasSuffix applies the HasSuffix predicate on the "request_path" field.
func RequestPathHasSuffix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasSuffix(FieldRequestPath, v))
}

// RequestPathEqualFold applies the EqualFold predicate on the "request_path" field.
func RequestPathEqualFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEqualFold(FieldRequestPath, v))
}

// RequestPathContainsFold applies the ContainsFold predicate on the "request_path" field.
func RequestPathContainsFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContainsFold(FieldRequestPath, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContainsFold(FieldStatus, v))
}

// TurnCountEQ applies the EQ predicate on the "turn_count" field.
func TurnCountEQ(v int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldTurnCount, v))
}

// TurnCountNEQ applies the NEQ predicate on the "turn_count" field.
func TurnCountNEQ(v int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldTurnCount, v))
}

// TurnCountIn applies the In predicate on the "turn_count" field.
func TurnCountIn(vs ...int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldTurnCount, vs...))
}

// TurnCountNotIn applies the NotIn predicate on the "turn_count" field.
func TurnCountNotIn(vs ...int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldTurnCount, vs...))
}

// TurnCountGT applies the GT predicate on the "turn_count" field.
func TurnCountGT(v int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldTurnCount, v))
}

// TurnCountGTE applies the GTE predicate on the "turn_count" field.
func TurnCountGTE(v int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldTurnCount, v))
}

// TurnCountLT applies the LT predicate on the "turn_count" field.
func TurnCountLT(v int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldTurnCount, v))
}

// TurnCountLTE applies the LTE predicate on the "turn_count" field.
func TurnCountLTE(v int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldTurnCount, v))
}

// SourceRequestCountEQ applies the EQ predicate on the "source_request_count" field.
func SourceRequestCountEQ(v int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldSourceRequestCount, v))
}

// SourceRequestCountNEQ applies the NEQ predicate on the "source_request_count" field.
func SourceRequestCountNEQ(v int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldSourceRequestCount, v))
}

// SourceRequestCountIn applies the In predicate on the "source_request_count" field.
func SourceRequestCountIn(vs ...int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldSourceRequestCount, vs...))
}

// SourceRequestCountNotIn applies the NotIn predicate on the "source_request_count" field.
func SourceRequestCountNotIn(vs ...int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldSourceRequestCount, vs...))
}

// SourceRequestCountGT applies the GT predicate on the "source_request_count" field.
func SourceRequestCountGT(v int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldSourceRequestCount, v))
}

// SourceRequestCountGTE applies the GTE predicate on the "source_request_count" field.
func SourceRequestCountGTE(v int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldSourceRequestCount, v))
}

// SourceRequestCountLT applies the LT predicate on the "source_request_count" field.
func SourceRequestCountLT(v int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldSourceRequestCount, v))
}

// SourceRequestCountLTE applies the LTE predicate on the "source_request_count" field.
func SourceRequestCountLTE(v int) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldSourceRequestCount, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldOutputTokens, v))
}

// TotalTokensEQ applies the EQ predicate on the "total_tokens" field.
func TotalTokensEQ(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldTotalTokens, v))
}

// TotalTokensNEQ applies the NEQ predicate on the "total_tokens" field.
func TotalTokensNEQ(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldTotalTokens, v))
}

// TotalTokensIn applies the In predicate on the "total_tokens" field.
func TotalTokensIn(vs ...int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldTotalTokens, vs...))
}

// TotalTokensNotIn applies the NotIn predicate on the "total_tokens" field.
func TotalTokensNotIn(vs ...int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldTotalTokens, vs...))
}

// TotalTokensGT applies the GT predicate on the "total_tokens" field.
func TotalTokensGT(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldTotalTokens, v))
}

// TotalTokensGTE applies the GTE predicate on the "total_tokens" field.
func TotalTokensGTE(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldTotalTokens, v))
}

// TotalTokensLT applies the LT predicate on the "total_tokens" field.
func TotalTokensLT(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldTotalTokens, v))
}

// TotalTokensLTE applies the LTE predicate on the "total_tokens" field.
func TotalTokensLTE(v int64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldTotalTokens, v))
}

// ActualCostEQ applies the EQ predicate on the "actual_cost" field.
func ActualCostEQ(v float64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldActualCost, v))
}

// ActualCostNEQ applies the NEQ predicate on the "actual_cost" field.
func ActualCostNEQ(v float64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldActualCost, v))
}

// ActualCostIn applies the In predicate on the "actual_cost" field.
func ActualCostIn(vs ...float64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldActualCost, vs...))
}

// ActualCostNotIn applies the NotIn predicate on the "actual_cost" field.
func ActualCostNotIn(vs ...float64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldActualCost, vs...))
}

// ActualCostGT applies the GT predicate on the "actual_cost" field.
func ActualCostGT(v float64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldActualCost, v))
}

// ActualCostGTE applies the GTE predicate on the "actual_cost" field.
func ActualCostGTE(v float64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldActualCost, v))
}

// ActualCostLT applies the LT predicate on the "actual_cost" field.
func ActualCostLT(v float64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldActualCost, v))
}

// ActualCostLTE applies the LTE predicate on the "actual_cost" field.
func ActualCostLTE(v float64) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldActualCost, v))
}

// QualityStatusEQ applies the EQ predicate on the "quality_status" field.
func QualityStatusEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldQualityStatus, v))
}

// QualityStatusNEQ applies the NEQ predicate on the "quality_status" field.
func QualityStatusNEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldQualityStatus, v))
}

// QualityStatusIn applies the In predicate on the "quality_status" field.
func QualityStatusIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldQualityStatus, vs...))
}

// QualityStatusNotIn applies the NotIn predicate on the "quality_status" field.
func QualityStatusNotIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldQualityStatus, vs...))
}

// QualityStatusGT applies the GT predicate on the "quality_status" field.
func QualityStatusGT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldQualityStatus, v))
}

// QualityStatusGTE applies the GTE predicate on the "quality_status" field.
func QualityStatusGTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldQualityStatus, v))
}

// QualityStatusLT applies the LT predicate on the "quality_status" field.
func QualityStatusLT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldQualityStatus, v))
}

// QualityStatusLTE applies the LTE predicate on the "quality_status" field.
func QualityStatusLTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldQualityStatus, v))
}

// QualityStatusContains applies the Contains predicate on the "quality_status" field.
func QualityStatusContains(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContains(FieldQualityStatus, v))
}

// QualityStatusHasPrefix applies the HasPrefix predicate on the "quality_status" field.
func QualityStatusHasPrefix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasPrefix(FieldQualityStatus, v))
}

// QualityStatusHasSuffix applies the HasSuffix predicate on the "quality_status" field.
func QualityStatusHasSuffix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasSuffix(FieldQualityStatus, v))
}

// QualityStatusEqualFold applies the EqualFold predicate on the "quality_status" field.
func QualityStatusEqualFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEqualFold(FieldQualityStatus, v))
}

// QualityStatusContainsFold applies the ContainsFold predicate on the "quality_status" field.
func QualityStatusContainsFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContainsFold(FieldQualityStatus, v))
}

// QualityErrorsIsNil applies the IsNil predicate on the "quality_errors" field.
func QualityErrorsIsNil() predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIsNull(FieldQualityErrors))
}

// QualityErrorsNotNil applies the NotNil predicate on the "quality_errors" field.
func QualityErrorsNotNil() predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotNull(FieldQualityErrors))
}

// ExportableEQ applies the EQ predicate on the "exportable" field.
func ExportableEQ(v bool) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldExportable, v))
}

// ExportableNEQ applies the NEQ predicate on the "exportable" field.
func ExportableNEQ(v bool) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldExportable, v))
}

// CaptureStatusEQ applies the EQ predicate on the "capture_status" field.
func CaptureStatusEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldCaptureStatus, v))
}

// CaptureStatusNEQ applies the NEQ predicate on the "capture_status" field.
func CaptureStatusNEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldCaptureStatus, v))
}

// CaptureStatusIn applies the In predicate on the "capture_status" field.
func CaptureStatusIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldCaptureStatus, vs...))
}

// CaptureStatusNotIn applies the NotIn predicate on the "capture_status" field.
func CaptureStatusNotIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldCaptureStatus, vs...))
}

// CaptureStatusGT applies the GT predicate on the "capture_status" field.
func CaptureStatusGT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldCaptureStatus, v))
}

// CaptureStatusGTE applies the GTE predicate on the "capture_status" field.
func CaptureStatusGTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldCaptureStatus, v))
}

// CaptureStatusLT applies the LT predicate on the "capture_status" field.
func CaptureStatusLT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldCaptureStatus, v))
}

// CaptureStatusLTE applies the LTE predicate on the "capture_status" field.
func CaptureStatusLTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldCaptureStatus, v))
}

// CaptureStatusContains applies the Contains predicate on the "capture_status" field.
func CaptureStatusContains(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContains(FieldCaptureStatus, v))
}

// CaptureStatusHasPrefix applies the HasPrefix predicate on the "capture_status" field.
func CaptureStatusHasPrefix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasPrefix(FieldCaptureStatus, v))
}

// CaptureStatusHasSuffix applies the HasSuffix predicate on the "capture_status" field.
func CaptureStatusHasSuffix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasSuffix(FieldCaptureStatus, v))
}

// CaptureStatusEqualFold applies the EqualFold predicate on the "capture_status" field.
func CaptureStatusEqualFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEqualFold(FieldCaptureStatus, v))
}

// CaptureStatusContainsFold applies the ContainsFold predicate on the "capture_status" field.
func CaptureStatusContainsFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContainsFold(FieldCaptureStatus, v))
}

// SessionSourceEQ applies the EQ predicate on the "session_source" field.
func SessionSourceEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldSessionSource, v))
}

// SessionSourceNEQ applies the NEQ predicate on the "session_source" field.
func SessionSourceNEQ(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldSessionSource, v))
}

// SessionSourceIn applies the In predicate on the "session_source" field.
func SessionSourceIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldSessionSource, vs...))
}

// SessionSourceNotIn applies the NotIn predicate on the "session_source" field.
func SessionSourceNotIn(vs ...string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldSessionSource, vs...))
}

// SessionSourceGT applies the GT predicate on the "session_source" field.
func SessionSourceGT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldSessionSource, v))
}

// SessionSourceGTE applies the GTE predicate on the "session_source" field.
func SessionSourceGTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldSessionSource, v))
}

// SessionSourceLT applies the LT predicate on the "session_source" field.
func SessionSourceLT(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldSessionSource, v))
}

// SessionSourceLTE applies the LTE predicate on the "session_source" field.
func SessionSourceLTE(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldSessionSource, v))
}

// SessionSourceContains applies the Contains predicate on the "session_source" field.
func SessionSourceContains(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContains(FieldSessionSource, v))
}

// SessionSourceHasPrefix applies the HasPrefix predicate on the "session_source" field.
func SessionSourceHasPrefix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasPrefix(FieldSessionSource, v))
}

// SessionSourceHasSuffix applies the HasSuffix predicate on the "session_source" field.
func SessionSourceHasSuffix(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldHasSuffix(FieldSessionSource, v))
}

// SessionSourceEqualFold applies the EqualFold predicate on the "session_source" field.
func SessionSourceEqualFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEqualFold(FieldSessionSource, v))
}

// SessionSourceContainsFold applies the ContainsFold predicate on the "session_source" field.
func SessionSourceContainsFold(v string) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldContainsFold(FieldSessionSource, v))
}

// RetentionUntilEQ applies the EQ predicate on the "retention_until" field.
func RetentionUntilEQ(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldRetentionUntil, v))
}

// RetentionUntilNEQ applies the NEQ predicate on the "retention_until" field.
func RetentionUntilNEQ(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldRetentionUntil, v))
}

// RetentionUntilIn applies the In predicate on the "retention_until" field.
func RetentionUntilIn(vs ...time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldRetentionUntil, vs...))
}

// RetentionUntilNotIn applies the NotIn predicate on the "retention_until" field.
func RetentionUntilNotIn(vs ...time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldRetentionUntil, vs...))
}

// RetentionUntilGT applies the GT predicate on the "retention_until" field.
func RetentionUntilGT(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldRetentionUntil, v))
}

// RetentionUntilGTE applies the GTE predicate on the "retention_until" field.
func RetentionUntilGTE(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldRetentionUntil, v))
}

// RetentionUntilLT applies the LT predicate on the "retention_until" field.
func RetentionUntilLT(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldRetentionUntil, v))
}

// RetentionUntilLTE applies the LTE predicate on the "retention_until" field.
func RetentionUntilLTE(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldRetentionUntil, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldStartedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldEndedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ConversationSession {
	return predicate.ConversationSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConversationSession) predicate.ConversationSession {
	return predicate.ConversationSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConversationSession) predicate.ConversationSession {
	return predicate.ConversationSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConversationSession) predicate.ConversationSession {
	return predicate.ConversationSession(sql.NotPredicates(p))
}
