// Code generated by ent, DO NOT EDIT.

package announcementemailbroadcast

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the announcementemailbroadcast type in the database.
	Label = "announcement_email_broadcast"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAnnouncementID holds the string denoting the announcement_id field in the database.
	FieldAnnouncementID = "announcement_id"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldBodyHTML holds the string denoting the body_html field in the database.
	FieldBodyHTML = "body_html"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTotalCount holds the string denoting the total_count field in the database.
	FieldTotalCount = "total_count"
	// FieldSentCount holds the string denoting the sent_count field in the database.
	FieldSentCount = "sent_count"
	// FieldFailedCount holds the string denoting the failed_count field in the database.
	FieldFailedCount = "failed_count"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// Table holds the table name of the announcementemailbroadcast in the database.
	Table = "announcement_email_broadcasts"
)

// Columns holds all SQL columns for announcementemailbroadcast fields.
var Columns = []string{
	FieldID,
	FieldAnnouncementID,
	FieldSubject,
	FieldBodyHTML,
	FieldStatus,
	FieldTotalCount,
	FieldSentCount,
	FieldFailedCount,
	FieldCreatedBy,
	FieldCreatedAt,
	FieldStartedAt,
	FieldCompletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultTotalCount holds the default value on creation for the "total_count" field.
	DefaultTotalCount int
	// DefaultSentCount holds the default value on creation for the "sent_count" field.
	DefaultSentCount int
	// DefaultFailedCount holds the default value on creation for the "failed_count" field.
	DefaultFailedCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the AnnouncementEmailBroadcast queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAnnouncementID orders the results by the announcement_id field.
func ByAnnouncementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnnouncementID, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByBodyHTML orders the results by the body_html field.
func ByBodyHTML(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBodyHTML, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTotalCount orders the results by the total_count field.
func ByTotalCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCount, opts...).ToFunc()
}

// BySentCount orders the results by the sent_count field.
func BySentCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSentCount, opts...).ToFunc()
}

// ByFailedCount orders the results by the failed_count field.
func ByFailedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedCount, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}
