// Code generated by ent, DO NOT EDIT.

package announcementemailbroadcast

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLTE(FieldID, id))
}

// AnnouncementID applies equality check predicate on the "announcement_id" field. It's identical to AnnouncementIDEQ.
func AnnouncementID(v int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldAnnouncementID, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldSubject, v))
}

// BodyHTML applies equality check predicate on the "body_html" field. It's identical to BodyHTMLEQ.
func BodyHTML(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldBodyHTML, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldStatus, v))
}

// TotalCount applies equality check predicate on the "total_count" field. It's identical to TotalCountEQ.
func TotalCount(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldTotalCount, v))
}

// SentCount applies equality check predicate on the "sent_count" field. It's identical to SentCountEQ.
func SentCount(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldSentCount, v))
}

// FailedCount applies equality check predicate on the "failed_count" field. It's identical to FailedCountEQ.
func FailedCount(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldFailedCount, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldCreatedAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldCompletedAt, v))
}

// AnnouncementIDEQ applies the EQ predicate on the "announcement_id" field.
func AnnouncementIDEQ(v int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldAnnouncementID, v))
}

// AnnouncementIDNEQ applies the NEQ predicate on the "announcement_id" field.
func AnnouncementIDNEQ(v int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNEQ(FieldAnnouncementID, v))
}

// AnnouncementIDIn applies the In predicate on the "announcement_id" field.
func AnnouncementIDIn(vs ...int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldIn(FieldAnnouncementID, vs...))
}

// AnnouncementIDNotIn applies the NotIn predicate on the "announcement_id" field.
func AnnouncementIDNotIn(vs ...int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNotIn(FieldAnnouncementID, vs...))
}

// AnnouncementIDGT applies the GT predicate on the "announcement_id" field.
func AnnouncementIDGT(v int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGT(FieldAnnouncementID, v))
}

// AnnouncementIDGTE applies the GTE predicate on the "announcement_id" field.
func AnnouncementIDGTE(v int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGTE(FieldAnnouncementID, v))
}

// AnnouncementIDLT applies the LT predicate on the "announcement_id" field.
func AnnouncementIDLT(v int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLT(FieldAnnouncementID, v))
}

// AnnouncementIDLTE applies the LTE predicate on the "announcement_id" field.
func AnnouncementIDLTE(v int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLTE(FieldAnnouncementID, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldContainsFold(FieldSubject, v))
}

// BodyHTMLEQ applies the EQ predicate on the "body_html" field.
func BodyHTMLEQ(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldBodyHTML, v))
}

// BodyHTMLNEQ applies the NEQ predicate on the "body_html" field.
func BodyHTMLNEQ(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNEQ(FieldBodyHTML, v))
}

// BodyHTMLIn applies the In predicate on the "body_html" field.
func BodyHTMLIn(vs ...string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldIn(FieldBodyHTML, vs...))
}

// BodyHTMLNotIn applies the NotIn predicate on the "body_html" field.
func BodyHTMLNotIn(vs ...string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNotIn(FieldBodyHTML, vs...))
}

// BodyHTMLGT applies the GT predicate on the "body_html" field.
func BodyHTMLGT(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGT(FieldBodyHTML, v))
}

// BodyHTMLGTE applies the GTE predicate on the "body_html" field.
func BodyHTMLGTE(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGTE(FieldBodyHTML, v))
}

// BodyHTMLLT applies the LT predicate on the "body_html" field.
func BodyHTMLLT(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLT(FieldBodyHTML, v))
}

// BodyHTMLLTE applies the LTE predicate on the "body_html" field.
func BodyHTMLLTE(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLTE(FieldBodyHTML, v))
}

// BodyHTMLContains applies the Contains predicate on the "body_html" field.
func BodyHTMLContains(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldContains(FieldBodyHTML, v))
}

// BodyHTMLHasPrefix applies the HasPrefix predicate on the "body_html" field.
func BodyHTMLHasPrefix(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldHasPrefix(FieldBodyHTML, v))
}

// BodyHTMLHasSuffix applies the HasSuffix predicate on the "body_html" field.
func BodyHTMLHasSuffix(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldHasSuffix(FieldBodyHTML, v))
}

// BodyHTMLEqualFold applies the EqualFold predicate on the "body_html" field.
func BodyHTMLEqualFold(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEqualFold(FieldBodyHTML, v))
}

// BodyHTMLContainsFold applies the ContainsFold predicate on the "body_html" field.
func BodyHTMLContainsFold(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldContainsFold(FieldBodyHTML, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldContainsFold(FieldStatus, v))
}

// TotalCountEQ applies the EQ predicate on the "total_count" field.
func TotalCountEQ(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldTotalCount, v))
}

// TotalCountNEQ applies the NEQ predicate on the "total_count" field.
func TotalCountNEQ(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNEQ(FieldTotalCount, v))
}

// TotalCountIn applies the In predicate on the "total_count" field.
func TotalCountIn(vs ...int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldIn(FieldTotalCount, vs...))
}

// TotalCountNotIn applies the NotIn predicate on the "total_count" field.
func TotalCountNotIn(vs ...int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNotIn(FieldTotalCount, vs...))
}

// TotalCountGT applies the GT predicate on the "total_count" field.
func TotalCountGT(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGT(FieldTotalCount, v))
}

// TotalCountGTE applies the GTE predicate on the "total_count" field.
func TotalCountGTE(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGTE(FieldTotalCount, v))
}

// TotalCountLT applies the LT predicate on the "total_count" field.
func TotalCountLT(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLT(FieldTotalCount, v))
}

// TotalCountLTE applies the LTE predicate on the "total_count" field.
func TotalCountLTE(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLTE(FieldTotalCount, v))
}

// SentCountEQ applies the EQ predicate on the "sent_count" field.
func SentCountEQ(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldSentCount, v))
}

// SentCountNEQ applies the NEQ predicate on the "sent_count" field.
func SentCountNEQ(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNEQ(FieldSentCount, v))
}

// SentCountIn applies the In predicate on the "sent_count" field.
func SentCountIn(vs ...int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldIn(FieldSentCount, vs...))
}

// SentCountNotIn applies the NotIn predicate on the "sent_count" field.
func SentCountNotIn(vs ...int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNotIn(FieldSentCount, vs...))
}

// SentCountGT applies the GT predicate on the "sent_count" field.
func SentCountGT(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGT(FieldSentCount, v))
}

// SentCountGTE applies the GTE predicate on the "sent_count" field.
func SentCountGTE(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGTE(FieldSentCount, v))
}

// SentCountLT applies the LT predicate on the "sent_count" field.
func SentCountLT(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLT(FieldSentCount, v))
}

// SentCountLTE applies the LTE predicate on the "sent_count" field.
func SentCountLTE(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLTE(FieldSentCount, v))
}

// FailedCountEQ applies the EQ predicate on the "failed_count" field.
func FailedCountEQ(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldFailedCount, v))
}

// FailedCountNEQ applies the NEQ predicate on the "failed_count" field.
func FailedCountNEQ(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNEQ(FieldFailedCount, v))
}

// FailedCountIn applies the In predicate on the "failed_count" field.
func FailedCountIn(vs ...int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldIn(FieldFailedCount, vs...))
}

// FailedCountNotIn applies the NotIn predicate on the "failed_count" field.
func FailedCountNotIn(vs ...int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNotIn(FieldFailedCount, vs...))
}

// FailedCountGT applies the GT predicate on the "failed_count" field.
func FailedCountGT(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGT(FieldFailedCount, v))
}

// FailedCountGTE applies the GTE predicate on the "failed_count" field.
func FailedCountGTE(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGTE(FieldFailedCount, v))
}

// FailedCountLT applies the LT predicate on the "failed_count" field.
func FailedCountLT(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLT(FieldFailedCount, v))
}

// FailedCountLTE applies the LTE predicate on the "failed_count" field.
func FailedCountLTE(v int) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLTE(FieldFailedCount, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLTE(FieldCreatedAt, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.FieldNotNull(FieldCompletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AnnouncementEmailBroadcast) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AnnouncementEmailBroadcast) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AnnouncementEmailBroadcast) predicate.AnnouncementEmailBroadcast {
	return predicate.AnnouncementEmailBroadcast(sql.NotPredicates(p))
}
