import { describe, expect, it } from 'vitest'

import en from '../locales/en'
import zh from '../locales/zh'

describe('upstream relay monitoring locales', () => {
  it('describes backend automatic monitoring without stale manual-only wording', () => {
    const zhDescription = zh.admin.upstreamRelayGroupMonitoring.monitoring.description
    const enDescription = en.admin.upstreamRelayGroupMonitoring.monitoring.description
    const zhStatus = zh.admin.upstreamRelayGroupMonitoring.monitoring.status
    const enStatus = en.admin.upstreamRelayGroupMonitoring.monitoring.status

    expect(zhDescription).toContain('自动应用需要显式开启')
    expect(zhDescription).not.toContain('当前阶段仅保存配置和支持手动触发')
    expect(zhStatus.running).toBe('自动监控运行中')
    expect(zhStatus.disabled).toBe('自动监控未启用')
    expect(zhStatus.detailBoth).toContain('自动同步')
    expect(zhStatus.detailBoth).toContain('自动探测')
    expect(zhStatus.detailRecommendationOnly).toContain('不会修改 priority')
    expect(enDescription).toContain('Auto-apply must be explicitly enabled')
    expect(enDescription).not.toContain('only saves configuration')
    expect(enStatus.running).toBe('Auto Monitoring Running')
    expect(enStatus.disabled).toBe('Auto Monitoring Not Enabled')
    expect(enStatus.detailRecommendationOnly).toContain('priority is not changed')
  })

  it('contains recommendation run source audit labels in both locales', () => {
    const zhRecommendations = zh.admin.upstreamRelayGroupMonitoring.recommendations
    const enRecommendations = en.admin.upstreamRelayGroupMonitoring.recommendations

    expect(zhRecommendations.colSource).toBe('来源')
    expect(zhRecommendations.sourceSystem).toBe('系统自动生成')
    expect(zhRecommendations.sourceManual).toBe('管理员手动生成')
    expect(zhRecommendations.appliedBySystem).toBe('系统自动应用')
    expect(zhRecommendations.appliedByManual).toBe('管理员手动应用')
    expect(enRecommendations.colSource).toBe('Source')
    expect(enRecommendations.sourceSystem).toBe('Generated by system')
    expect(enRecommendations.sourceManual).toBe('Generated manually')
    expect(enRecommendations.appliedBySystem).toBe('Applied by system')
    expect(enRecommendations.appliedByManual).toBe('Applied manually')
  })

  it('contains usage history tab and table labels in both locales', () => {
    const zhFeature = zh.admin.upstreamRelayGroupMonitoring
    const enFeature = en.admin.upstreamRelayGroupMonitoring

    expect(zhFeature.tabs.usageHistory).toBe('历史用量')
    expect(enFeature.tabs.usageHistory).toBe('Usage History')
    expect(zhFeature.usageHistory.description).toContain('最终日用量汇总')
    expect(enFeature.usageHistory.description).toContain('final daily usage summaries')
    expect(zhFeature.usageHistory.colDate).toBe('日期')
    expect(zhFeature.usageHistory.colGroup).toBe('分组')
    expect(zhFeature.usageHistory.colCost).toBe('Actual Cost')
    expect(zhFeature.usageHistory.colTokens).toBe('Token')
    expect(zhFeature.usageHistory.colCheckedAt).toBe('采集时间')
    expect(enFeature.usageHistory.colDate).toBe('Date')
    expect(enFeature.usageHistory.colGroup).toBe('Group')
    expect(enFeature.usageHistory.colCost).toBe('Actual Cost')
    expect(enFeature.usageHistory.colTokens).toBe('Tokens')
    expect(enFeature.usageHistory.colCheckedAt).toBe('Checked At')
  })
})
