// Code generated by ent, DO NOT EDIT.

package conversationexportjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the conversationexportjob type in the database.
	Label = "conversation_export_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFilters holds the string denoting the filters field in the database.
	FieldFilters = "filters"
	// FieldFormat holds the string denoting the format field in the database.
	FieldFormat = "format"
	// FieldEncoding holds the string denoting the encoding field in the database.
	FieldEncoding = "encoding"
	// FieldSessionCount holds the string denoting the session_count field in the database.
	FieldSessionCount = "session_count"
	// FieldTurnCount holds the string denoting the turn_count field in the database.
	FieldTurnCount = "turn_count"
	// FieldFileSize holds the string denoting the file_size field in the database.
	FieldFileSize = "file_size"
	// FieldS3Key holds the string denoting the s3_key field in the database.
	FieldS3Key = "s3_key"
	// FieldDownloadURLExpiresAt holds the string denoting the download_url_expires_at field in the database.
	FieldDownloadURLExpiresAt = "download_url_expires_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// Table holds the table name of the conversationexportjob in the database.
	Table = "conversation_export_jobs"
)

// Columns holds all SQL columns for conversationexportjob fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldFilters,
	FieldFormat,
	FieldEncoding,
	FieldSessionCount,
	FieldTurnCount,
	FieldFileSize,
	FieldS3Key,
	FieldDownloadURLExpiresAt,
	FieldExpiresAt,
	FieldErrorMessage,
	FieldCreatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldStartedAt,
	FieldCompletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultFormat holds the default value on creation for the "format" field.
	DefaultFormat string
	// FormatValidator is a validator for the "format" field. It is called by the builders before save.
	FormatValidator func(string) error
	// DefaultEncoding holds the default value on creation for the "encoding" field.
	DefaultEncoding string
	// EncodingValidator is a validator for the "encoding" field. It is called by the builders before save.
	EncodingValidator func(string) error
	// DefaultSessionCount holds the default value on creation for the "session_count" field.
	DefaultSessionCount int64
	// DefaultTurnCount holds the default value on creation for the "turn_count" field.
	DefaultTurnCount int64
	// DefaultFileSize holds the default value on creation for the "file_size" field.
	DefaultFileSize int64
	// S3KeyValidator is a validator for the "s3_key" field. It is called by the builders before save.
	S3KeyValidator func(string) error
	// ErrorMessageValidator is a validator for the "error_message" field. It is called by the builders before save.
	ErrorMessageValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ConversationExportJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFormat orders the results by the format field.
func ByFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFormat, opts...).ToFunc()
}

// ByEncoding orders the results by the encoding field.
func ByEncoding(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncoding, opts...).ToFunc()
}

// BySessionCount orders the results by the session_count field.
func BySessionCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionCount, opts...).ToFunc()
}

// ByTurnCount orders the results by the turn_count field.
func ByTurnCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTurnCount, opts...).ToFunc()
}

// ByFileSize orders the results by the file_size field.
func ByFileSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileSize, opts...).ToFunc()
}

// ByS3Key orders the results by the s3_key field.
func ByS3Key(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3Key, opts...).ToFunc()
}

// ByDownloadURLExpiresAt orders the results by the download_url_expires_at field.
func ByDownloadURLExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadURLExpiresAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}
